### PR TITLE
Adjust new tab icon to fix weight issues

### PR DESCRIPTION
**Pull request by tesk9**
### Before

Screen Shot 2023-01-24 at 2 16 01 PM

### Feedback round 1

Screen Shot 2023-01-24 at 2 15 40 PM

### Feedback round 2

Screen Shot 2023-01-24 at 4 07 10 PM

### Feedback round 3

image

### After

Screen Shot 2023-01-24 at 4 38 21 PM

### Before

Screen Shot 2023-01-24 at 2 15 57 PM

### Feedback round 1

Screen Shot 2023-01-24 at 2 15 45 PM

### Feedback round 2

Screen Shot 2023-01-24 at 4 07 22 PM

### Feedback round 3

Screen Shot 2023-01-24 at 4 23 41 PM

### After

Screen Shot 2023-01-24 at 4 38 29 PM

### Before

Screen Shot 2023-01-24 at 2 18 59 PM

### Feedback round 1

Screen Shot 2023-01-24 at 2 16 41 PM

### Feedback round 2

Screen Shot 2023-01-24 at 4 07 51 PM

### Feedback round 3

image

image

### After

Screen Shot 2023-01-24 at 4 39 17 PM

cc @NoRedInk/design

### CODE REVIEW

**Comment by bendansby** [comment]
Looks much nicer! Maybe a smidge smaller?

**Comment by staceyadams** [comment]
> fix weight issues

UiIcon's new year's resolution? 😂

**Comment by tesk9** [comment]
1 smidge smaller! I can do another smidge smaller still if you want? 

And Stacey, I fully support a consistent-ify-the-weights-across-all-the-icons NY's resolution!

**Comment by bendansby** [comment]
Let's do oooone more smidge. That will be the clinching smidge I strongly feel

**Comment by tesk9** [comment]
Haha this is so solidly into I-can't-tell-if-anything-is-changing territory. Is it actually getting smidged smaller??? I'm like.. not 100% sure 😅 How's it looking to you?

**Comment by bendansby** [comment]
Yeah it does look the same! Hmm maybe we want a skosh or a soupçon instead of a smidge. We can go ahead and merge and play with it later. It's already a big improvement!

**Comment by tesk9** [comment]
Haha 1 final smoosh just to see if we can get it closer and then let's call it 😅

**Comment by bendansby** [comment]
Oh there we go! Nice smoosh 👍

**Comment by staceyadams** [comment]
> And Stacey, I fully support a consistent-ify-the-weights-across-all-the-icons NY's resolution!

I was making a bad weight loss NY's joke 😅 but I also support consistent-ifying! (don't have bandwidth to tweak the icons though 😞)

**Comment by bendansby** [comment]
For the record, I enjoyed the joke

**Review by charbelrami — APPROVED** [review]

**Pull request merged**
