### PR TITLE
Mobile tab styles

### PR DESCRIPTION
**Pull request by bendansby**
Adjusts maximal Tabs styles to fit on a narrow viewport.

image

### CODE REVIEW

**Comment by bendansby** [comment]
@tesk9 I was hoping to sneak this in to improve the teacher experience a bit, but I know this is janky so if you want to ixnay it, totally understand!

Screenshot 2023-07-13 at 12 49 10 PM
Screenshot 2023-07-13 at 12 48 46 PM

**Review by tesk9 — APPROVED** [review]
Looks really nice! I'm excited about this!

**Comment by tesk9** [comment]
Oh could you please fix the unused imports before merging? 🙏

**Comment by bendansby** [comment]
Awesome, thanks for the review!

**Pull request merged**
