### PR TITLE
expose heading styles

### PR DESCRIPTION
**Pull request by brookeangel**
For https://github.com/NoRedInk/noredink-ui/issues/343

### CODE REVIEW

**Comment by BrianHicks** [comment]
thanks, I had this on my list but you beat me to it! 😁

**Comment by brookeangel** [comment]
aw man, this fails CI because apparently exposing constructors constitutes a major version bump 😢 - do you think I should just make a v3 to avoid the major version bump conundrum?

**Comment by BrianHicks** [comment]
I think it'd be fine to a major bump here. I don't see how this would cause breaking behavior in any application—it's not like we could have constructed or matched on a `Style` value before!

**Comment by BrianHicks** [comment]
let's ask in Slack though.

**Comment by brookeangel** [comment]
Thanks for asking!

**Pull request merged**
