### PR TITLE
Bat/disabled switch

### PR DESCRIPTION
**Pull request by tesk9**
Part of https://github.com/NoRedInk/noredink-ui/issues/1098

Fixes A11-1712

Screen Shot 2022-10-04 at 4 09 46 PM
Screen Shot 2022-10-04 at 4 09 41 PM
Screen Shot 2022-10-04 at 4 10 01 PM
Screen Shot 2022-10-04 at 4 09 52 PM

@NoRedInk/design how's this? did I get all the grays right? 😅

### CODE REVIEW

**Comment by bendansby** [comment]
Ahh looks so beautimous insofar as such a design can be beautimous! Thank you!

**Comment by tesk9** [comment]
Ping, @omnibs 😄

**Comment by omnibs** [comment]
@tesk9 will review today, i was ooo last week

**Comment by tesk9** [comment]
Oh, sorry about the ping then! No hurry on this PR, I just went through and pinged folks on all my older PRs today. Thanks for reviewing!

**Pull request merged**
