### PR TITLE
New Version, to fix installation issues

### PR DESCRIPTION
**Pull request by tesk9**
I tried to update the monolith to use the new version of `accessible-html-with-css` and whew ended up being a huge pain. And now I'm over here, deleting old & unused components 🤷‍♀️ 

At any rate:
- the removed components should not be in use in the monolith, content-creation, or tutorials. (One exception: there's a single use of ClickableSvg.V1 in Block/Editor.elm. I figure that's a small enough change I can just do it...)
- you shouldn't see the "Atomic Design type" fieldset in the lower left of the styleguide, because it didn't seem to me that it caught on
- tesk9/palette 3.0.0 renamed Color -> SolidColor. The helpers that changed aren't used on the monolith.
- SegmentedControl editors/@NoRedInk/team-raven  -- in the upgrade from V13 -> V14, I think you all didn't bring the tests along. Heads up in case this is an accidental omission 😄 

```
This is a MAJOR change.

---- REMOVED MODULES - MAJOR ----

    Nri.Ui.Accordion.V2
    Nri.Ui.ClickableSvg.V1
    Nri.Ui.Icon.V3
    Nri.Ui.Icon.V4
    Nri.Ui.Icon.V5
    Nri.Ui.InputStyles.V2
    Nri.Ui.Message.V1
    Nri.Ui.Message.V2
    Nri.Ui.Modal.V3
    Nri.Ui.SegmentedControl.V11
    Nri.Ui.SegmentedControl.V12
    Nri.Ui.SegmentedControl.V13
    Nri.Ui.Text.V2
    Nri.Ui.Text.V4


---- Nri.Ui.Colors.Extra - MAJOR ----

    Changed:
      - fromCssColor : Color -> Color
      + fromCssColor : Css.Color -> SolidColor.SolidColor

      - toCssColor : Color -> Color
      + toCssColor : SolidColor.SolidColor -> Css.Color
```

### CODE REVIEW

**Comment by BrianHicks** [comment]
>  in the upgrade from V13 -> V14, I think you all didn't bring the tests along.

No, I really don't think that was intentional. I see a review request from @nunocf—Nuno, do you wanna fix it or shall I?

**Comment by nunocf** [comment]
@BrianHicks if you have the spare time, it would be nice, I'm currently trying to wrap up a bit of work today before being away for 3 days.
If it's not urgent, I can definitely pick it up when I'm back!

**Comment by BrianHicks** [comment]
I don't think it's that urgent, no. 😄 Unless… @tesk9 are you gonna be blocked on us doing that? (Seems like no but I wanna make sure.)

**Comment by tesk9** [comment]
No, not blocked at all! Just wanted to mention it to you since I noticed it, not because I think it's vital/urgent. Thanks!

**Review by BrianHicks — APPROVED** [review]
red gif for a red diff!

image

**Pull request merged**
