### PR TITLE
Icon examples

### PR DESCRIPTION
**Pull request by bendansby**
Cleans up the display of icon examples.

image

### CODE REVIEW

**Comment by bendansby** [comment]
@tesk9 I hid the icon names because I find it easier to scan, though obviously the names have value for reference and searching. How hard would it be to add a show/hide name toggle?

**Comment by tesk9** [comment]
I _gasped_ this is so pretty!

I don't think it would be hard to add a "Show names" checkbox! Shall I branch off this and add that?

**Comment by tesk9** [comment]
I added a checkbox to every icon display page that controls whether to show the names or not, and I added some percy snapshots for when we're showing the icon names! 😄 

I didn't change any styles or anything like that

**Comment by bendansby** [comment]
Wooo thanks so much! Love it

**Review by tesk9 — APPROVED** [review]

**Pull request merged**
