### PR TITLE
Biggify modals

### PR DESCRIPTION
**Pull request by BrianHicks**
This makes the modals grow up until they are 50px away from the top and bottom. They're so biggified now!

🍐 with @quelledanielle 

## Long Content

image

## Short Content

image

### CODE REVIEW

**Comment by BrianHicks** [comment]
@NoRedInk/design does this look OK to y'all?

**Comment by staceyadams** [comment]
Woo! When they are not fully grown, can they be vertically centered?

**Comment by quelledanielle** [comment]
Screenshot_2019-11-12 Style Guide

@BrianHicks @tesk9 I modified the `Accessibility.Modal.Copy`, so now it's not just a copy of [`tesk9/modal`](https://package.elm-lang.org/packages/tesk9/modal/7.0.0/Accessibility-Modal) 🤔

**Comment by quelledanielle** [comment]
Oops I forgot the branch was off `pin-everything`

**Comment by BrianHicks** [comment]
@quelledanielle did you end up merging this into `master`?

**Comment by quelledanielle** [comment]
@BrianHicks No, it merged into #405 and I'm not sure what to do about it 😆

**Comment by BrianHicks** [comment]
=> #410

**Pull request merged**
