### PR TITLE
:wrench: Fix checkbox guidance alignment

### PR DESCRIPTION
**Pull request by tesk9**
Fixes https://github.com/NoRedInk/noredink-ui/issues/1454

- adds new ClickableText.caption size for use with Text.caption-size text
- adjusts the Checkbox implementation to reposition the guidance appropriately

## :framed_picture: What does this change look like?

Screen Shot 2023-08-10 at 4 04 50 PM

I added a new section to the Checkbox example that always shows the guidance, because I feel like we've had trouble with alignment 🐛 s on the guidance that Percy could have caught.

Does this alignment look okay to you?

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
    - [x] Component docs include a changelog
    - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
    - [x] The Component Catalog is updated to use the newest version, if appropriate
    - [x] The Component Catalog example version number is updated, if appropriate
    - [x] Any new customizations are available from the Component Catalog
    - [x] The component example still has:
        - an accurate preview
        - valid sample code
        - correct keyboard behavior
        - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
    - e.g., as a dev, I can conveniently add an `nriDescription`
    - and adding a new feature to the component will _not_ require major API changes to the component
- [x] If this is a new major version of the component, our team has stories created to upgrade all instances of the old component. Here are links to the stories:
  - this is not a new major version

### CODE REVIEW

**Comment by bendansby** [comment]
Oh, that's great, thanks for the quick fix! And for the new ClickableText size, I had that on my mental to-do list. No more [this](https://github.com/NoRedInk/NoRedInk/pull/45169/files#diff-b0cf00c7e131218a6e7e7fd496189a1e3993b9af60a89825561df42da2244f4dR329)!

It looks sliiightly misaligned sans ClickableText, but that could be attributable to the caprices of letterforms or oddly numbered pixels
Napkin 15 08-10-23, 3 19 16 PM

**Comment by tesk9** [comment]
Okay! So I think the problem is that the ClickableText ends up making the entire guidance line 17.5px tall instead of 13px.

The extra height seems to be coming from two places:
- it uses line-height normal, which for 13px ends up (in chrome) at 16.5px
- appearsInline adds the border bottom, which adds 1px to the bottom

image

I don't want to end up in the CSS weeds of ClickableText, so I think what I'm going to do is try to get the plain `guidance` view's top alignment slightly higher, and not worry as much about the guidanceHtml alignment. (Especially since `guidance` is much more used.)

**Comment by bendansby** [comment]
Awesome, thank you!

**Comment by tesk9** [comment]
Okay! I did remove `line-height: normal` from the ClickableText, so hopefully that doesn't cause any issues! I improved the example for the inline appearance of ClickabelText, which will also help us identify problems sooner rather than later.

Screen Shot 2023-08-11 at 4 21 19 PM

--

For the checkbox icon, I think that the transparent border around the icon (which is there, as I recall, for high contrast mode) was causing the misalignment. I adjusted the label container up to account for the margin. Look okay?

Screen Shot 2023-08-11 at 4 21 30 PM

**Comment by bendansby** [comment]
I like it, appreciate the fine-tuning!

**Review by mfonism — APPROVED** [review]
This is fantastic.

Thank you Tessa!

aligned-carla-delaney

**Pull request merged**
