### PR TITLE
[PHX-594] Eliminate the jitter of QB positioning.

### PR DESCRIPTION
**Pull request by micahhahn**
This PR makes the QB invisible for the brief bit of time while we calculate measurements. This eliminates the jitter that has been throwing some students off when the QuestionBox moves around. 

🎩 to Tessa for the idea. 

# :wrench: Modifying a component

## Context

[PHX-594](https://linear.app/noredink/issue/PHX-594/scaffolding-container-jumps-when-step-changes)

## :framed_picture: What does this change look like?

https://user-images.githubusercontent.com/12899207/227378960-55eb7256-b3dd-478e-9119-77f9be85a148.mov

- [x] Follow the the [Guidelines for an optimal design ping](https://paper.dropbox.com/doc/Guidelines-for-Sharing-User-Facing-Changes-with-Design--BpL8hpJLMugy6033aT5m0JdaAg-bdKGQtYH9qO9I00hUkA6k) to add helpful screenshots/videos for design.
- [x] ~@ mention the design team on this PR to request approval on your changes. A designer will "thumbs up" react to your PR if they approve it, or will leave comments if it's not quite approved yet.~ Design didn't change, simply a bugfix

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
    - [x] Component docs include a changelog
    - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
    - [x] The Component Catalog is updated to use the newest version, if appropriate
    - [x] The Component Catalog example version number is updated, if appropriate
    - [x] Any new customizations are available from the Component Catalog
    - [x] The component example still has:
        - an accurate preview
        - valid sample code
        - correct keyboard behavior
        - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
    - e.g., as a dev, I can conveniently add an `nriDescription`
    - and adding a new feature to the component will _not_ require major API changes to the comopnent

### CODE REVIEW

**Comment by micahhahn** [comment]
@tesk9 Hey Max passed along your ideas for reducing the jitter with the QuestionBox! Thanks! 

I implemented them here, I also tweak the percy generation to happen *after* clicking the measure button so that we see some output in visual diffs.

**Review by tesk9 — APPROVED** [review]
Looks great, thanks!

**Comment by micahhahn** [comment]
> Oh actually, remembered something! Could you please update the pointingTo docs to be explicit that the QB won't render without the measurements & add a patch change note to the top of the QB docs? Thanks!

Done!

**Comment by micahhahn** [comment]
I pulled back the changes to "puppeteer-test.js" as it seemed to be flakey (showed box in correct positions on 6afc489 and showed no boxes at all in 86929a0).  Best just to not have boxes at all I think

**Pull request merged**
