### PR TITLE
Assignment Library disabled checklist and radio button styling

### PR DESCRIPTION
**Pull request by mandla-noredink**
# :wrench: Modifying a component

## Context

This PR updates the check box and radio button styling as per [GRO-1390](https://linear.app/noredink/issue/GRO-1390/assignment-library-disabled-checklist-styling).

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
  - [x] Component docs include a changelog
  - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
  - [x] The Component Catalog is updated to use the newest version, if appropriate
  - [x] The Component Catalog example version number is updated, if appropriate
  - [x] Any new customizations are available from the Component Catalog
  - [x] The component example still has:
    - an accurate preview
    - valid sample code
    - correct keyboard behavior
    - correct and comprehensive guidance around how to use the component
- [-] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
  - e.g., as a dev, I can conveniently add an `nriDescription`
  - and adding a new feature to the component will _not_ require major API changes to the component
- [-] If this is a new major version of the component, our team has stories created to upgrade all instances of the old component. Here are links to the stories:
  - add your story links here OR just write this is not a new major version
- [x] Please assign the following reviewers (applicable Sep 2023–Dec 2023):
  - [x] [a11y-volunteer-reviewers](https://github.com/orgs/NoRedInk/teams/volunteer-a11y-reviewers) - Someone from this group will review your PR in full.
  - [x]  [team-accessibilibats-a11ybats](https://github.com/orgs/NoRedInk/teams/team-accessibilibats-a11ybats) - Someone from this group will review your PR for ACCESSIBILITY ONLY.
  - [x]  Someone from your team who can review requirements from your team's perspective. (This could be the same person from the [a11y-volunteer-reviewers](https://github.com/orgs/NoRedInk/teams/volunteer-a11y-reviewers) group if you'd like.)
  - [x]  If there are user-facing changes, a designer:
    - For writing-related component changes, add Stacey (staceyadams)
    - For quiz engine-related components, add Ravi (ravi-morbia)
    - For a11y-related changes to general components, add Ben (bendansby)
    - For general component-related changes or if you’re not sure about something, add the Design group (NoRedInk/design)

### CODE REVIEW

**Review by BrianHicks — APPROVED** [review]
abstract-noise-gif-by-lefler

**Comment by BrianHicks** [comment]
even better, here's the diff: https://percy.io/NoRedInk/NoRedInk-UI/builds/30342551/changed/1677710116?browser=chrome&browser_ids=48&subcategories=approved&viewLayout=overlay&viewMode=new&width=1280&widths=375,1280

**Comment by ravi-morbia** [comment]
@mandla-noredink the text label for NotSelected x Enabled should be Gray 20.

All the other colors look good!

It is hard for me to tell if the inner shadow is accurate in Percy so I might need to check that once it is merged.

**Comment by ravi-morbia** [comment]
@mandla-noredink I see this merged. Was that after making the change above?

**Comment by ravi-morbia** [comment]
Gotcha for future reference, all user-facing PRs will have a designer as a reviewer.

**Comment by BrianHicks** [comment]
Yes, I know. This was just a mistake. Again, sorry about that!

**Comment by ravi-morbia** [comment]
No worries!

**Pull request merged**
