### PR TITLE
add sticky headers to sortable tables

### PR DESCRIPTION
**Pull request by BrianHicks**
# :wrench: Modifying a component

API design note: unlike tabs, we don't currently know any use-case aside from stickiness where we'd need to set the page background color separate from stickiness, so I combined them!

## Context

Part of ADM-705

## :framed_picture: What does this change look like?

No changes to the table component except that now the header can be made sticky.

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
    - [x] Component docs include a changelog
    - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
    - [x] The Component Catalog is updated to use the newest version, if appropriate
    - [x] The Component Catalog example version number is updated, if appropriate
    - [x] Any new customizations are available from the Component Catalog
    - [x] The component example still has:
        - an accurate preview
        - valid sample code
        - correct keyboard behavior
        - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
    - e.g., as a dev, I can conveniently add an `nriDescription`
    - and adding a new feature to the component will _not_ require major API changes to the component

### CODE REVIEW

**Comment by BrianHicks** [comment]
@bendansby do the Percy changes look OK to you? A couple sub-5px changes that are going to be very tricky to eliminate.

**Comment by bendansby** [comment]
Looks like table header height got reduced a bit? Why's that?

**Comment by BrianHicks** [comment]
It now has to use an inset box shadow instead of a border. We need this because we collapse border tables, making the header bottom border stick to the table instead of the header. I tried adding a bit of padding to the bottom to fix this, but it doubles the border height. If the 3px difference matters for us, I can spend some more time on it.

**Review by charbelrami — APPROVED** [review]
Looks great!

**Comment by bendansby** [comment]
Can we just use a fixed table header height?

**Comment by BrianHicks** [comment]
I can try. What height would you like?

**Comment by bendansby** [comment]
45px plz

**Comment by tesk9** [comment]
(Fixed _minimum_ table height, please! The height will still need to expand if users adjust their font size settings or if the text in the heading is quite long)

**Comment by BrianHicks** [comment]
turns out the header is 47.5px tall right now, and 46 in this branch. I'll try to make it 45, though.

**Comment by BrianHicks** [comment]
well it turns out the margin was messed up—the text was much closer to the border, despite the container being smaller.

Here's how I've adjusted it (15px from baseline to border)

image

and the currently-released version (also 15px from baseline to border):

image

We can shrink that to 45px default height if you want. No big deal at this point. Since it turns out it was a padding thing, much easier to adjust.

**Comment by bendansby** [comment]
Oh great, that looks better and sure let's go for 45. Thanks!

**Comment by BrianHicks** [comment]
45ified!

image

**Comment by bendansby** [comment]
image

**Review by charlieshanley — APPROVED** [review]
Looks good!
giphy - 2023-04-04T133728 104

**Pull request merged**
