### PR TITLE
Ink/ally/text area update

### PR DESCRIPTION
**Pull request by allymcknight**
This PR fixes a bug in the TextArea styling code which prevented the label from changing color upon text area focus. 

# OUTFOXES

https://www.pivotaltracker.com/story/show/162593210

### CODE REVIEW

**Comment by allymcknight** [comment]
@lukewestby Hey Luke! Tessa and I thought you might be a good person to review this PR given that there's custom element resizing stuff.

**Comment by allymcknight** [comment]
@lukewestby sure! mind checking it out now?

**Comment by allymcknight** [comment]
@lukewestby ping!

**Comment by tesk9** [comment]
@allymcknight I think Luke is OOO until January 3. Maybe worth re-teambot-ing?

**Pull request merged**
