### PR TITLE
Make Google Classroom logo smaller

### PR DESCRIPTION
**Pull request by Arkham**
Otherwise in Chrome the right hand side gets cut by our default icon
positioning padding.

Before:

Screenshot 2020-02-19 at 12 01 58

After:

Screenshot 2020-02-19 at 12 19 34

Tested on Mac OS with:
- Chrome
- Safari
- Firefox

As surfaced here: https://github.com/NoRedInk/NoRedInk/pull/26374#issuecomment-588189920

### CODE REVIEW

**Comment by tesk9** [comment]
I think I get it now! And I'm fully 👍

I removed the transforms and just kept the image tag (with your new 19 width and height values). Does that look okay to you? If so, I'm very happy for this to merge & proceed!

**Comment by Arkham** [comment]
Hah, I'm afraid the transforms were needed

Screenshot 2020-02-20 at 10 28 53

I've noticed we have those transforms for the copy icon here: https://github.com/NoRedInk/noredink-ui/blob/master/src/Nri/Ui/UiIcon/V1.elm#L135

So I would guess they are needed to center the icon? I don't know SVG well enough :/

**Comment by tesk9** [comment]
@Arkham Weird, I can't reproduce the view that you're showing!

Screen Shot 2020-02-20 at 10 25 25 AM
Screen Shot 2020-02-20 at 10 25 07 AM
Screen Shot 2020-02-20 at 10 24 30 AM

I don't know why the transformations would be necessary. 🤔 If we've got the viewbox set to be "0 0 20 20", and the child positioned at (0,0) with width 19 and height 19, the child should be comfortably in there.

**Comment by jwoudenberg** [comment]
Hi there! Sorry for pushing to your branch! We've resolved some merge conflicts resulting from moving all `noredink-ui` code into a subdirectory, to support an upcoming merge into our private repository. More details are on Slack, please reach out to Puffins if you run into any issues or have any questions!

**Pull request closed without merging**
