### PR TITLE
Add `rightIcon` to `RadioButton`

### PR DESCRIPTION
**Pull request by celsobonutti**
# :wrench: Modifying a component

## Context

https://noredink.slack.com/archives/C0VVDLEES/p1706727431228269

## :framed_picture: What does this change look like?

image

## Component completion checklist

- [X] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [X] Changes are clearly documented
  - [X] Component docs include a changelog
  - [X] Any new exposed functions or properties have docs
- [X] Changes extend to the Component Catalog
  - [X] The Component Catalog is updated to use the newest version, if appropriate
  - [X] The Component Catalog example version number is updated, if appropriate
  - [X] Any new customizations are available from the Component Catalog
  - [X] The component example still has:
    - an accurate preview
    - valid sample code
    - correct keyboard behavior
    - correct and comprehensive guidance around how to use the component
- [X] Changes to the component are tested/the new version of the component is tested
- [X] Component API follows standard patterns in noredink-ui
  - e.g., as a dev, I can conveniently add an `nriDescription`
  - and adding a new feature to the component will _not_ require major API changes to the component
- [X] Please assign the following reviewers:
  - [X]  Someone from your team who can review your PR in full and review requirements from your team's perspective.
  - [X]  [team-accessibilibats-a11ybats](https://github.com/orgs/NoRedInk/teams/team-accessibilibats-a11ybats) - Someone from this group will review your PR for accessibility and adherence to component library foundations.
  - [X]  If there are user-facing changes, a designer. (You may want to direct your designer to the [deploy preview](https://github.com/NoRedInk/noredink-ui#reviews--preview-environments) for easy review):
    - For writing-related component changes, add Stacey (staceyadams)
    - For quiz engine-related components, add Ravi (ravi-morbia)
    - For a11y-related changes to general components, add Ben (bendansby)
    - For general component-related changes or if you’re not sure about something, add the Design group (NoRedInk/design)

### CODE REVIEW

**Review by bendansby — APPROVED** [review]
Can we turn off the icon by default in the component catalog example?

**Comment by bendansby** [comment]
Is there a way to set the icon color besides inheriting the label color or whatever color the icon intrinsically has? Won't be a problem since the GA is always turquoise but if this is used with a different icon we probably won't want it to be gray/blue

**Review by tesk9 — COMMENTED** [review]
Is it expected that, when the content is Premium locked, unlocked, or vouchered, the rightIcon doesn't show?

My expectation would have been that the Grading Assistant icon would sometimes function kind of like a mini upsell indicator, if that makes sense?

**Comment by celsobonutti** [comment]
> Can we turn off the icon by default in the component catalog example?

Sure

> Is there a way to set the icon color besides inheriting the label color or whatever color the icon intrinsically has?

We can make it a record of { icon : Svg, color : Css.Color }. yes.

> Is it expected that, when the content is Premium locked, unlocked, or vouchered, the rightIcon doesn't show?
My expectation would have been that the Grading Assistant icon would sometimes function kind of like a mini upsell indicator, if that makes sense?

Hmm, I think it makes sense. @bendansby what do you think? in this case, should we prioritize the icon from `rightIcon`, the Premium Flag icon, or just show both?

**Comment by tesk9** [comment]
> We can make it a record of { icon : Svg, color : Css.Color }

You shouldn't need to do this. If you pass in the icon like `RadioButton.icon (Svg.withColor Colors.red UiIcon.arrowLeft)`, you should get this:
image

You can test this by editing https://github.com/NoRedInk/noredink-ui/blob/master/component-catalog/src/CommonControls.elm#L339 to set the color.

**Comment by bendansby** [comment]
Let's show both icons, premium flag always at the end

**Comment by celsobonutti** [comment]
@tesk9 @bendansby problems adressed 😊

**Comment by bendansby** [comment]
Thank you!

**Review by tesk9 — APPROVED** [review]
Thanks!

**Review by charlieshanley — APPROVED** [review]

**Pull request merged**
