### PR TITLE
Favicon and setup cleanup

### PR DESCRIPTION
**Pull request by tesk9**
- Adds favicon
- Fixes Sprite SVG console errors
- Removes unused questionbox subscribe causing console errors

There should be a cute favicon now:
Screen Shot 2023-02-14 at 11 58 24 AM

And there should no longer be errors in the console.

### CODE REVIEW

**Comment by krinhorn** [comment]
Oops, I didn't realize until I saw this screenshot that it should probably have the title `Component Catalog | NoRedInk`? (or similar, so that "Component Catalog" is first in the title.)

**Comment by tesk9** [comment]
Oh, I think we've been treating "NoRedInk" as part of the name -- like it wasn't "The Styleguide" it was "The NoRedInk Styleguide." We can change that though, if you want!

**Comment by krinhorn** [comment]
Yeah, I figured! Only reason it's even important IMO is for easily distinguishing tabs, and I figured people might have multiple "NoRedInk" tabs open... but maybe the favicon helps!

**Review by charbelrami — APPROVED** [review]

**Comment by tesk9** [comment]
I'm open to either way! Will you make an issue if you'd like it changed, please?

**Pull request merged**
