### PR TITLE
Lab/change clickable text alignemnt

### PR DESCRIPTION
**Pull request by tesk9**
Part of https://www.pivotaltracker.com/story/show/165216675

### Lock
Screen Shot 2019-04-09 at 4 50 22 PM

### Performance
Screen Shot 2019-04-09 at 4 50 12 PM

### Help
Screen Shot 2019-04-09 at 4 50 00 PM

I kinda feel like the lock and the performance icon look less good? But the help icon _definitely_ looks better and that's the one we use all over the place.

cc @NoRedInk/design

### CODE REVIEW

**Comment by bendansby** [comment]
The lock and performance are visually bottom heavy, so that makes sense. Looks good!

**Comment by bendansby** [comment]
Actually, I think there could stand to be a pixel or two more space between the icon and label. Let me see...

**Comment by bendansby** [comment]
Yeah, 1 more px on medium and 2 on large. How's that for picky?

**Comment by tesk9** [comment]
How's this?

Screen Shot 2019-04-10 at 9 20 56 AM

**Comment by bendansby** [comment]
Beautimous!

**Pull request merged**
