### PR TITLE
Add select v4

### PR DESCRIPTION
**Pull request by tremlab**
using custom select arrows in V4.

### CODE REVIEW

**Comment by tremlab** [comment]
image
@bendansby How does this look?  We have some questions:

- do we need error styles?
- do we need label option?

thanks!

**Comment by bendansby** [comment]
Ideal would be to have the states and label option as seen in the style guide, but I leave it up to y'all as to whether to include them in this PR.

Style note: we don't want the inner shadow. But that made realize we do want a hard drop shadow to match our medium buttons! I've updated the Zeplin if you'd like to add that in this PR. If not, just removing the inner shadow would be fine.

Thanks for working on this!!

**Comment by michaelglass** [comment]
updated elm-format. Can you use the new elm-format here before you merge? <3

**Comment by stoeffel** [comment]
@tremlab is this still in use or can we close this?

**Pull request closed without merging**
