### PR TITLE
disallow major changes in Travis

### PR DESCRIPTION
**Pull request by BrianHicks**
A repo administrator can still override this check if we really need to publish a major change, but let's catch the common case.

Aside: is this decision documented anywhere? I've seen several people mention it… could someone in the know please add the rationale to the README or something?

```text
$ make diff                                                                                                                                                                                    master :: 8m :: ⬡
if (elm-package diff | tee /dev/stderr | grep -q MAJOR); then echo "MAJOR changes are not allowed!"; exit 1; fi
Comparing NoRedInk/noredink-ui 4.2.0 to local changes...
This is a MAJOR change.

------ Changes to module Nri.Ui.SegmentedControl.V3 - MAJOR ------

    Added:
        type CssClasses

    Changed:
      - styles : Nri.Ui.Styles.V1.Styles Basics.Never Nri.Ui.SegmentedControl.V3.CssClass msg
      + styles : Nri.Ui.Styles.V1.Styles Basics.Never Nri.Ui.SegmentedControl.V3.CssClasses msg



------ Changes to module Nri.Ui.SegmentedControl.V4 - MAJOR ------

    Added:
        type CssClasses

    Changed:
      - styles : Nri.Ui.Styles.V1.Styles Basics.Never Nri.Ui.SegmentedControl.V4.CssClass msg
      + styles : Nri.Ui.Styles.V1.Styles Basics.Never Nri.Ui.SegmentedControl.V4.CssClasses msg



MAJOR changes are not allowed!
make: *** [diff] Error 1
```

### CODE REVIEW

**Comment by BrianHicks** [comment]
example fail: https://travis-ci.org/NoRedInk/noredink-ui/builds/360285053?utm_source=github_status&utm_medium=notification

**Comment by BrianHicks** [comment]
@joneshf this does the thing you mentioned wanting!

**Comment by BrianHicks** [comment]
example success: https://travis-ci.org/NoRedInk/noredink-ui/builds/360286049?utm_source=github_status&utm_medium=notification

**Comment by jwoudenberg** [comment]
This is so awesome!

> Aside: is this decision documented anywhere? I've seen several people mention it… could someone in the know please add the rationale to the README or something?

We have some in a paper doc, but I can see that's not the first place one might look. Will create a PR!

**Pull request merged**
