### PR TITLE
Lab/modal without bottom buttons

### PR DESCRIPTION
**Pull request by tesk9**
Screen Shot 2019-10-11 at 10 09 12 AM
Screen Shot 2019-10-11 at 10 08 13 AM
Screen Shot 2019-10-11 at 10 07 55 AM

<details>
<summary>Second Swing
</summary>

Screen Shot 2019-10-10 at 4 35 21 PM
Screen Shot 2019-10-10 at 4 35 12 PM
Screen Shot 2019-10-10 at 4 35 03 PM
Screen Shot 2019-10-10 at 4 34 50 PM
Screen Shot 2019-10-10 at 4 33 52 PM

</details>

<details>
<summary>First swing
</summary>

## No bottom buttons
Screen Shot 2019-10-09 at 3 01 19 PM
Screen Shot 2019-10-09 at 3 01 10 PM

## Hidden title
Screen Shot 2019-10-09 at 3 00 55 PM
Screen Shot 2019-10-09 at 3 00 43 PM

</details>

cc @NoRedInk/design so this is what I've been working on. Visually speaking, does this seem like it's on the right track?

### CODE REVIEW

**Comment by bendansby** [comment]
Looking good! I'm pleased to see that the no-buttons version doesn't have an empty stump of a footer — though I'd make the shadow stronger. For the no-title version, can we position the X such that it doesn't collide with content?

**Comment by tesk9** [comment]
>  For the no-title version, can we position the X such that it doesn't collide with content?

Should I make the content more narrow, or move the content down?

**Comment by tesk9** [comment]
Some options:

Screen Shot 2019-10-10 at 1 51 27 PM
Screen Shot 2019-10-10 at 1 50 54 PM


And you're thinking move the X for only when there's not a visible title...?

**Comment by bendansby** [comment]
Yeah, more like the 2nd. I've updated and uglified the modal screen in the Zeplin style guide to provide some specific guidance on padding, sizing, etc. for all the modal elements. LMK if you need any other scenarios or elements covered! https://zpl.io/a7WzDva

**Comment by tesk9** [comment]
thank you!!!

**Comment by tesk9** [comment]
I updated the description with some new screenshots! Any concerns? Or places where I've messed up?

One thing I noticed is that the focus outline looks less polished with the new positioning -- maybe not worth worrying about, given Ink's work on improving focus management site-wide.

**Comment by bendansby** [comment]
Nice! I'm wondering if it would be possible for the title-less style to start off with top padding but then have content scroll to the top edge?

Another note is that the footer-less bottom shadow could be a bit more prominent, as seen in the Zeplin.

**Comment by tesk9** [comment]
> I'm wondering if it would be possible for the title-less style to start off with top padding but then have content scroll to the top edge?

Definitely! I misunderstood the zeplin 😅 

> footer-less bottom shadow could be a bit more prominent, as seen in the Zeplin.

Oh! I thought it was just a color change, which I made. I guess the shadow is 40px high rather than 20px in the footerless shadow.. Will try to get it!

**Comment by tesk9** [comment]
When I used the 40px from the zeplin, it looked a lot bolder than I expected. I pulled it back a litttle.

How's this looking? (Sorry for a million small pings!)

**Comment by bendansby** [comment]
Looks great!!

**Comment by tesk9** [comment]
NAILED IT first try! :P 

Thank you thank you!!!

**Comment by michaelglass** [comment]
@Arkham and I are playing with the API here

**Comment by michaelglass** [comment]
we think we can abstract away some of the focusable stuff. But we've made some progress

**Comment by michaelglass** [comment]
I started doing a refactor that exposes configured functions rather than passing around settings to each child... 

pros:
makes it harder / impossible to configure something wrong in two places

cons: type signatures get pretty darned complicated

thoughts?

example: 

instead of

```
outerModal: isVisible -> List InnerThing -> TotalThing

innerThing1: isVisible -> param -> InnerThing
innerThing2; isVisible -> param -> InnerThing
```

we could

```
type alias InnerThingFuncs = 
  {  innerThing1: param -> InnerThing
   , innerThing2: param -> InnerThing
  }

outerModal: isVisible -> (InnerThingFuncs -> List InnerThing) -> TotalThing
```

**Comment by tesk9** [comment]
I think I like it!!!

**Comment by tesk9** [comment]
@michaelglass I'm planning to not touch this PR until you're happy with the refactor/API. Sound good?

**Comment by tesk9** [comment]
@michaelglass Hiya! Wanted to check in on this -- do you have work you'd like to see go in with this?

**Comment by michaelglass** [comment]
@tesk9 I think I'm done here

**Comment by tesk9** [comment]
@michaelglass I LOVE these changes, thank you! Way nicer!!!

**Pull request merged**
