### PR TITLE
Bat/border checkbox

### PR DESCRIPTION
**Pull request by tesk9**
Fixes https://github.com/NoRedInk/noredink-ui/issues/965

Adds an azure border for the fully-selected checkbox. 

@NoRedInk/design is this sufficient? I'm pretty sure there's an optical illusion making it look like there's a strip of the light blue right above the shadow?  (Please play with the deploy preview -- I want to be sure the toggling experience is what you'd like too, if you don't mind! 🙏  In particular, LMK if I need to hold this until the focus ring changes.)

### CODE REVIEW

**Comment by bendansby** [comment]
Thank you! I added a border to the unchecked state as well to improve contrast (though not fully compliant; we might need an HC mode for that) and to make things match better between states.

**Comment by tesk9** [comment]
Oooo I like it! It makes the difference between enabled and disabled states more clear too.

Should we add the border to the indeterminate and the premium-locked checkbox icons too?

**Comment by bendansby** [comment]
yeeaah 👍

**Comment by bendansby** [comment]
Yup yup!

**Pull request merged**
