### PR TITLE
New info svg icon

### PR DESCRIPTION
**Pull request by mandla-noredink**
This PR adds a new information icon to UiIcon V1, as specified in [the design spec](https://linear.app/noredink/issue/RVN-1144/card-views-clean-up-tasks) for Writing Portfolio cards:

Normal:
Screenshot 2022-07-22 at 12 39 59

Highlighted:
Screenshot 2022-07-22 at 12 40 10

### CODE REVIEW

**Comment by BrianHicks** [comment]
🤔 the `i` looks off-center here. Is that just me?

**Comment by mandla-noredink** [comment]
> 🤔 the `i` looks off-center here. Is that just me?

I thought so too, but it kinda does in the figma example as well. That had me thinking it was just how it's wanted, but happy to change if you think it should be dead centre.

**Comment by BrianHicks** [comment]
Hmmmmm. Can we ask @staceyadams to verify?

**Comment by staceyadams** [comment]
Centered please! I think I knocked it off-center in Figma at some point and didn't realize 😅

**Review by tesk9 — APPROVED** [review]
Feel free to merge as soon as the `i` is centered!

**Pull request merged**
