### PR TITLE
:star2: Extracting Outline from the monolith

### PR DESCRIPTION
**Pull request by tesk9**
Replicates Nri.Outline and Nri.Outline.Keyed in noredink-ui.

Fixes https://github.com/NoRedInk/noredink-ui/issues/499

## About the component

Nri.Outline and Nri.Outline.Keyed are used in the monolith for Peer Review topic sentences, Outline Draggable, and Outline Multiple Choice questions.

Nri.Ui.Outline.V1 is intended to be used as a simplified replacement. When upgrading to Nri.Ui.Outline.V1, feel free to delete [the assorted component example](https://staging.noredink.com/assorted_components/doodad/Nri%2FOutline.elm) as well.

## :framed_picture: What does this change look like?

image

image

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with this component in mind
- [x] Component has clear documentation
- [x] Component is in the Component Catalog
    - [x] Component is categorized reasonably (see [Category](https://github.com/NoRedInk/noredink-ui/blob/master/component-catalog-app/Category.elm) for all the currently available categories). The component can be in multiple categories, if appropriate.
    - [x] Component has a representative preview for the Component Catalog cards (bonus points for making it delightful!)
    - [x] Component has a customizable example. Aim for having _every_ possible supported version of the component displayable through the configuration on this page. (Protip: This is handy for testing expected behavior!)
    - [x] The customizable example produces sample code
    - [x] The component's example page includes keyboard behavior, if any
    - [x] The component's example page includes guidance around how to use the component, if necessary
- [x] Component is tested
    - axe checks and percy snapshots will be automatically added for every component. However, if you want to customize _when_ the checks and snapshots are made, you will need to make changes to [script/puppeteer-tests.js](https://github.com/NoRedInk/noredink-ui/blob/master/script/puppeteer-tests.js).
    - there are 2 ways to add Elm tests:
        - if you want to test the Component Catalog example directly, add ProgramTest-style tests under `component-catalog/tests`
        - if you want to test the component directly, add tests under `tests/Spec`. Historically, this has been the more popular Elm testing strategy for noredink-ui.
- [ ] Component API follows standard patterns in noredink-ui
  - I tried to minimize changes to the API, in the interest of making the upgrade path simple. Future versions of the component might want to use an attributes-list pattern instead.
- [x] Please assign the following reviewers (applicable Sep 2023–Dec 2023):
    - [ ] [a11y-volunteer-reviewers](https://github.com/orgs/NoRedInk/teams/volunteer-a11y-reviewers) - Someone from this group will review your PR in full.
    - [x]  [team-accessibilibats-a11ybats](https://github.com/orgs/NoRedInk/teams/team-accessibilibats-a11ybats) - Someone from this group will review your PR for ACCESSIBILITY ONLY.
    - [x]  Someone from your team who can review requirements from your team's perspective.
    - [x]  A designer, maybe - If there are user-facing changes, follow the guidelines above to assign the correct designer.

### CODE REVIEW

**Review by bendansby — APPROVED** [review]
That preview is SO CUTE

**Comment by bendansby** [comment]
Can we add it to the Instructional category?

**Review by charbelrami — COMMENTED** [review]
Looks great! I noticed some commented code in `src/Nri/Ui/Outline/V1.elm`. Is this meant to be kept for future reference or can it be removed?

**Comment by tesk9** [comment]
@charbelrami I think the commented out code is in doc comments, so it should be fine! It'll be included in the package docs (e.g., like the [way Block has commented-out code](https://package.elm-lang.org/packages/NoRedInk/noredink-ui/latest/Nri-Ui-Block-V4#view))

**Review by charbelrami — APPROVED** [review]

**Comment by charbelrami** [comment]
thank you!

**Pull request merged**
