### PR TITLE
bump from 6.2.0 -> 6.3.0

### PR DESCRIPTION
**Pull request by brookeangel**
This will release Button V7

> Hello there, wonderful author of widgets!
> This is `Nri.Ui.Friendly.AI.V1` speaking to you!
> Are you looking to get this awesome work reviewed as quickly as possible, so you can start putting it to use?
> Then feel free to ask Teambot to assign a reviewer to your PR
>
> https://nri-teambot.herokuapp.com
>
> It's best if we have separate pull requests for code changes and package version bumps. If you're just changing code, great! If you're just bumping the version, check out https://github.com/NoRedInk/noredink-ui#deploying.

### CODE REVIEW

**Comment by brookeangel** [comment]
Thanks for the review!

**Comment by brookeangel** [comment]
Hah shoot, I think I tagged the wrong commit (the one before I updated the elm.json with the new version) and now it won't let me publish: 

```
The code tagged as 6.3.0 in git does not match the code in your working
directory. This means you have commits or local changes that are not going to be
published!
```

You think it's ok to change and force push a tag @BrianHicks ?

**Comment by BrianHicks** [comment]
If nobody's pulled it, it's probably fine. But I'd say something in #eng-frontend along the lines of "hey doing this thing; be aware there may be a conflict if you've pulled in the last 30 minutes"

(but also I can't remember if we allow force pushes on this repo! 😵)

**Comment by brookeangel** [comment]
Woo ok success, I didn't even need to force push to delete the tag it turns out!

**Pull request merged**
