### PR TITLE
Add FocusRing example

### PR DESCRIPTION
**Pull request by tesk9**
Adds FocusRing helpers to Component Catalog as an atom, to hopefully make the FocusRing behavior more clear and discoverable.

localhost_8000_ (8)

### CODE REVIEW

**Comment by krinhorn** [comment]
@bendansby  (Tessa is out for a few days) `styles` is the default focus ring. [[Source: Tessa's video demo, around 12:00 mins](https://www.dropbox.com/scl/fi/e5o8zqbx65iri706661u8/video1232435053.mp4?rlkey=e3rfqz5cgtvmqh1ydotacf51z&dl=0)] I'm not sure why it's called `styles` - maybe that's the confusion and it should possibly be renamed?

**Comment by bendansby** [comment]
Yeah, renaming to `default` or whatever would make sense. To my earlier point it'd also be nice to see some more real-noredink-world examples for `default`.

**Review by krinhorn — APPROVED** [review]
Nothing blocking that I can see. Let's merge this while Tessa is OOO if Ben & Charbel don't have any blockers.

**Review by bendansby — APPROVED** [review]
No blockage here

**Review by charbelrami — APPROVED** [review]

**Pull request merged**
