### PR TITLE
Update disabled menu styles

### PR DESCRIPTION
**Pull request by tesk9**
Part of https://github.com/NoRedInk/noredink-ui/issues/1098

Fixes A11-1715

Screen Shot 2022-10-05 at 10 13 04 AM
Screen Shot 2022-10-05 at 10 13 11 AM

cc @NoRedInk/design

### CODE REVIEW

**Comment by bendansby** [comment]
The colors here look darker than https://github.com/NoRedInk/noredink-ui/pull/1112 — screenshot anomaly, my imagination, or real?

**Comment by bendansby** [comment]
Thanks!

**Comment by tesk9** [comment]
With gray92:
image

**Review by omnibs — APPROVED** [review]
Changes look good!

**Pull request merged**
