### PR TITLE
Tessa/add animated icons

### PR DESCRIPTION
**Pull request by tesk9**
Extract hamburger-x-animated-icon to noredink-ui, re-done as an Svg so that we can use ClickableSvg (which in turn will resolve fixes A11-1495)

https://user-images.githubusercontent.com/8811312/188029681-62421f4a-e116-4e15-a0c1-dc622caf79c7.mov

cc @NoRedInk/design the animation is slightly different. I was trying to avoid the viewBox clipping the edges of the svg. Is this okay with you?

### CODE REVIEW

**Comment by bendansby** [comment]
Looks nice, but is it less wide than before?

**Comment by tesk9** [comment]
I don't think it's narrower than it was before. I did zoom-out the viewbox a little bit to make room in the animation at the halfway point so the edges wouldn't get cut off, so the SVG is less trim-to-the-edges than they usually are. 🤔 I added 2px of whitespace to each side. 

The current version is 22x17, although the X does look like it has extra whitespace on the sides:

Screen Shot 2022-09-01 at 5 50 19 PM
Screen Shot 2022-09-01 at 5 50 03 PM

Accounting for 2px of whitespace on each side, the icon at 26px width should look pretty similar to the screenshots above.  Looks like the rects end up at 22.4x4.5.

image

Comparing that back again to the published version:
image
Looks like 22x3...

SO! I think the rects are fatter, more than anything else. Although they do _look_ narrower. I will narrow them up, and see if that resolves the discrepancies.

Is it cool if I remove UiIcon.hamburger from the styleguide and mark it as deprecated, so I don't need to update that one to match?

**Comment by tesk9** [comment]
Better?

https://user-images.githubusercontent.com/8811312/188033087-4264f864-df7c-4341-808d-420628cb709b.mov

**Comment by tesk9** [comment]
Dang -- just discovered that the transforms don't transition well in safari. I'll address it before merging this.

**Comment by bendansby** [comment]
Looks great, thanks for adjusting that!

**Pull request merged**
