### PR TITLE
Use palette rather than color

### PR DESCRIPTION
**Pull request by tesk9**
This change will cause CI failures since it requires a major version bump. I think that the`highContrast` helper from the palette library leads to a nicer looking colors view, though!

### Before

Screen Shot 2019-06-21 at 10 10 14 AM

### After

Screen Shot 2019-06-21 at 10 06 30 AM

### CODE REVIEW

**Comment by brookeangel** [comment]
Hey @tesk9 - I think this one has a real build failure (bad import Color in a few places) - want to fix it so I can merge it with the batch?

**Comment by brookeangel** [comment]
I'm confused by the output of CI here - looks like axe errors went down. But it still made CI fail?
```
Makefile:14: recipe for target 'axe-report' failed

make[1]: *** [axe-report] Error 1

make[1]: Leaving directory '/home/travis/build/NoRedInk/noredink-ui'

Makefile:5: recipe for target 'test' failed

make: *** [test] Error 2
```

**Comment by tesk9** [comment]
Oh -- maybe this fixed contrast issues? Let me see... axe wasn't on this repo when I made this PR initially 😅

**Comment by tesk9** [comment]
```
Success! Compiled 85 modules.
if (npx elm diff | tee /dev/stderr | grep -q MAJOR); then echo "MAJOR changes are not allowed!"; exit 1; fi
This is a MAJOR change.
---- Nri.Ui.Colors.Extra - MAJOR ----
    Added:
        fromCssColor : Css.Color -> Color.Color
        toCssColor : Color.Color -> Css.Color
    
    Removed:
        toCoreColor : Color -> Color
MAJOR changes are not allowed!
Makefile:22: recipe for target 'diff' failed
make: *** [diff] Error 1
The command "$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make ci" exited with 2.

```

@brookeangel  I think it's failing for the right reason now!

**Comment by tesk9** [comment]
@brookeangel shhhhh don't look at the last commit or tell anyone about it :P

**Comment by brookeangel** [comment]
Great, @tesk9 - merging this and then the others 🙈 
Then reverting that commit 😆

**Pull request merged**
