### PR TITLE
use onClickStopPropagation in tooltip.V1

### PR DESCRIPTION
**Pull request by brookeangel**
Fixes a bug where clicking a tooltip was triggering too many effects in https://github.com/NoRedInk/NoRedInk/pull/25320

The deprecated version of tooltip in the monolith also stops propagation.

### CODE REVIEW

**Comment by bendansby** [comment]
We would only need to allow for click if we are not able to allow the user to mouse off the question mark onto the tooltip to click a link without the tooltip disappearing. If we can achieve that, hover only is fine.

**Comment by brookeangel** [comment]
ah ok forgot we had some links in "?" tooltips - we aren't quite there in this version (this just added some accessibility stuff)

**Comment by brookeangel** [comment]
@bendansby - was doing some research into "links on hover tooltips" and it's do-able but seems to not be accessibility best practice (it requires having the <button> that surrounds the trigger content also contain the content of the tooltip bubble, which would be confusing to screen readers).

Also, this module isn't in use anywhere yet so it can change, but I initially made all the "?"-triggered tooltips click-only based on https://inclusive-components.design/tooltips-toggletips/

Any ways you can think of around the accessibility snafu?

**Comment by brookeangel** [comment]
Gonna merge this in on CI 🍏 and add hover in the next edit, since this just fixes a bug

**Pull request merged**
