### PR TITLE
A11-3081 Create Message V4

### PR DESCRIPTION
**Pull request by charbelrami**
# :wrench: Modifying a component

## Context

- adds `status` role
- removes `alertdialog` role
- moves custom attributes and role to a div containing the icon and text
- makes this div programmatically focusable

[A11-3081 : Update Nri.Ui.Message to work nicely for AT notifications](https://linear.app/noredink/issue/A11-3081/update-nriuimessage-to-work-nicely-for-at-notifications)

## :framed_picture: What does this change look like?

Screenshot 2023-07-25 at 18 39 13
Screenshot 2023-07-25 at 18 39 34
Screenshot 2023-07-25 at 18 39 47

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
    - [x] Component docs include a changelog
    - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
    - [x] The Component Catalog is updated to use the newest version, if appropriate
    - [x] The Component Catalog example version number is updated, if appropriate
    - [x] Any new customizations are available from the Component Catalog
    - [x] The component example still has:
        - an accurate preview
        - valid sample code
        - correct keyboard behavior
        - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
    - e.g., as a dev, I can conveniently add an `nriDescription`
    - and adding a new feature to the component will _not_ require major API changes to the component

### CODE REVIEW

**Comment by tesk9** [comment]
I think the codeDetails styles don't look quite right:

image


And the `x` when the message is dismissable has moved:

image

**Review by tesk9 — COMMENTED** [review]
Code looks great!

Just want to be sure that the visual diffs below are intended before we merge:

Screen Shot 2023-08-01 at 3 14 28 PM
Screen Shot 2023-08-01 at 3 15 56 PM

**Comment by charbelrami** [comment]
yes, I thought it would make them more consistent. Do you think it's good? @tesk9 @bendansby

**Comment by bendansby** [comment]
The problem I see is that one-line tiny messages no longer vertically align with the icon.

**Comment by charbelrami** [comment]
aligned icon

**Review by bendansby — APPROVED** [review]
Thanks!

**Comment by tesk9** [comment]
So just to confirm, @bendansby, both of these changes are fine/desired:

1. tiny message icon is center aligned against multi-line content

image

3. code details are tighter against the tiny message than they were previously

image

**Comment by bendansby** [comment]
1. Yep!
2. Having more space as in the before is preferred but it's not a hard requirement. (I mainly want to give it a whole new design)

**Review by tesk9 — APPROVED** [review]
Great! In that case, I think this is ready, unless Charbel wants to add the space back in 😄

**Comment by charbelrami** [comment]
Thanks! I removed the space between the message and the details in the tiny container to make it consistent with the other sizes, none of which have that space. I'll merge it for now, and if it doesn't look good, we can put it back.

**Pull request merged**
