### PR TITLE
Fix continous integration

### PR DESCRIPTION
**Pull request by nyghtly-derek**
Looks like Brian Hicks updated his GitHub username, which broke the link for `elm-forbid-import`. A quick update will fix it right up.

Also had to fix a couple test violations for stuff that merged while continuous integration was temporarily disabled.

--

For reference: [the original `shake ci` bug](https://github.com/NoRedInk/noredink-ui/actions/runs/9717162182/job/26822252853?pr=1683).

closing: https://linear.app/noredink/issue/FXN-3348/fix-continuous-integration-for-noredink-ui

### CODE REVIEW

**Comment by nyghtly-derek** [comment]
Okay, looks like we got further than before!

**Comment by zwilias** [comment]
Ah, back to the same, normal-ish flakes. Cool.

**Comment by nyghtly-derek** [comment]
Oh, just a flake! Thanks lol, I though something still needed to be fixed 😅 

I'll retry until it passes...

**Comment by nyghtly-derek** [comment]
Wow, is it actually this flakey?

**Review by zwilias — APPROVED** [review]
tysm @nyghtly-derek!

**Pull request merged**
