### PR TITLE
Respect prefers reduced motion

### PR DESCRIPTION
**Pull request by tesk9**
Adjusts spinningPencil and spinningDots and adds spinning in order to reduce motion when requested, while still providing a visual loading indicator.

<details><summary>Previous version of the description, before discussion on PR</summary>

The spinningPencil is a LOT when it just keeps rendered. This PR makes it respect prefers reduced motion settings. ... Which makes it much _less_ clear that it's meant to be a loading state. 

image

cc @NoRedInk/design 

</details>

### CODE REVIEW

**Comment by bendansby** [comment]
Would it be crazy to use dots instead of pencil when reduced motion is on?

**Comment by tesk9** [comment]
Interesting idea!

I think that would work if the dots didn't translate, but instead had their color transform in-place, you know?


https://user-images.githubusercontent.com/8811312/190831348-24eeddfd-4285-48ef-94db-831226dd1a6d.mov


Personally, I find the pencil & the dots a bit dizzying (hence the button to show them). Not having actual motion but just _implied_ motion would probably help!

I'll push up the code to use color transitions instead of rotations, so you can see it on this branch in the preview!

**Comment by tesk9** [comment]
https://user-images.githubusercontent.com/8811312/193638872-516fb396-3ded-471c-b4d3-00adb4334168.mov

@bendansby what do you think?

**Comment by bendansby** [comment]
Very cool! Is it possible for the two to share the same bounding box?

**Comment by tesk9** [comment]
Like so?

https://user-images.githubusercontent.com/8811312/193661040-fe3c8de1-5a70-48f9-859f-1b90f6e604e7.mov

**Comment by bendansby** [comment]
Nailed it, thank you!

**Pull request merged**
