### PR TITLE
Modal guidance

### PR DESCRIPTION
**Pull request by tesk9**
Component Catalog change only.

Fixes https://linear.app/noredink/issue/A11-4104/move-modal-guidance-from-text-field-to-about-section

Clarifies https://noredink.slack.com/archives/C02NMHB1K55/p1707433597293789?thread_ts=1707432784.790109&cid=C02NMHB1K55

image

### CODE REVIEW

**Review by bendansby — APPROVED** [review]
I'm not sure you actually need this since it's more a design-level thing:

> Pair the Modal. warning theme with the Button. danger theme and the Modal. info theme with the Button.primary theme.

**Comment by tesk9** [comment]
I buy that! I was wondering a bit about whether it made more sense to link to the styleguide anyway. Or I can cut it 🤔 

@krinhorn what do you think?

**Comment by krinhorn** [comment]
I like the idea of linking to the style guide if there's something about this in there. Otherwise I think @bendansby  & Design are in a better position to say if this kind of note is needed in the CC or if they specify this in their design specs/mockups.

**Review by krinhorn — APPROVED** [review]
Oops, didn't realize I was set as a reviewer! Looks good other than that last comment for Ben to address. Thank you!

**Comment by tesk9** [comment]
✂️  image ✂️

**Comment by bendansby** [comment]
That looks good. I think what modal styles to use will be adequately conveyed in each design.

**Pull request merged**
