### PR TITLE
Style code output

### PR DESCRIPTION
**Pull request by tesk9**
Component Catalog example code reskinning! 🎉 

| | Before | After |
| --- | --- | --- |
| w/1 example, mobile | image | Screenshot 2024-02-02 at 1 32 43 PM |
| w/1 example, desktop | image | Screenshot 2024-02-02 at 1 32 35 PM |
| w/2 examples, mobile | image | image |
| w/2 examples, desktop | image | image |

Based (roughly) off of https://cloud.antetype.com/exports/link/0499b00d-fe06-465c-a8e7-9e9f8f8e9efe/?starting=0&screen=id519257437l

### CODE REVIEW

**Review by bendansby — APPROVED** [review]
Oh man, just like in the movies! 🤩 

What do you think of dropping the `<details>` disclosure when there are multiple code samples and just displaying each one under a heading?

**Comment by tesk9** [comment]
> What do you think of dropping the <details> disclosure when there are multiple code samples and just displaying each one under a heading?

I think it would look nicer & would encourage people to use and maintain the code examples, and to think really carefully about the API.

But there are a couple of cases that make me hesitate:

### Sometimes there are lots of code examples:

Screenshot 2024-02-02 at 3 15 48 PM


### Sometimes the code samples are long and compex:

image

### And sometimes there's both! Lots of examples that are long and complicated:

Screenshot 2024-02-02 at 3 16 41 PM

**Comment by bendansby** [comment]
Oh, gotcha. Maybe not then. Could we just add 5-10px of spacing between each one? That will at least reduce the jumble a bit.

**Comment by tesk9** [comment]
image

**Comment by bendansby** [comment]
Dig it, thank you!

**Comment by tesk9** [comment]
I changed the button text to match your antetype too.

I think it looks nicer, but still a little confusing/cluttered once you start opening sections:
image

**Comment by bendansby** [comment]
Mm yeah, maybe a gray45 dividing line between each one would help separate? Could also go back to the original position and ClickableText style (except white) if that still feels too cluttered.

**Comment by tesk9** [comment]
Way better! Not as clean, but wayyyy less overwhelming!

image

**Comment by bendansby** [comment]
Nice, thanks for iterating on that!

**Comment by bendansby** [comment]
I think enforcing a 50/50 width would help with code readability and consistency 👍 

Incidentally, could we use baseFont for the About sections and have the same spacing below the headings as we have for Keyboard Support?

image

**Review by charbelrami — APPROVED** [review]
🤩

**Pull request merged**
