### PR TITLE
stop icons from shrinking and top-align them

### PR DESCRIPTION
**Pull request by BrianHicks**
More icons were shrinking (see https://github.com/NoRedInk/NoRedInk/issues/29526) and Stacey and Ben prefer they be top-aligned (see https://github.com/NoRedInk/NoRedInk/issues/29527.)

This PR fixes both!

image

image

image

image

@NoRedInk/design does that look ok to y'all?

### CODE REVIEW

**Comment by bendansby** [comment]
Can you post a single-line example too?

**Comment by BrianHicks** [comment]
oh, good catch… that looks worse. I'll see if I can get the best of both worlds real quick, mm?

image

**Comment by BrianHicks** [comment]
There. Now there's no change.

image

Oh… while I'm in here, do you want the icons in the large and banner-style warnings to be aligned top too? Now they look like so:

image

**Comment by BrianHicks** [comment]
that is, would it be better for them to look like this?

image

**Comment by staceyadams** [comment]
I like it in the middle in the large and banner styles because they are in a container.
I don't feel strongly either way though.

**Comment by bendansby** [comment]
Yeah, agreed

**Comment by BrianHicks** [comment]
works for me. No further work needed to keep them centered.

If y'all wanna check it out further the deploy preview is in the deploy/netlify check on this PR, currently https://deploy-preview-607--noredink-ui.netlify.app

**Review by juanedi — APPROVED** [review]

**Pull request merged**
