### PR TITLE
fix character headshot zoom in safari

### PR DESCRIPTION
**Pull request by BrianHicks**
# :wrench: Modifying a component

## Context

Once applied, you should be able to adjust text zoom in Safari without beheading Lindy.

The beheading happened because we were flipping Lindy's head and then moving it back into place by pixels. Chrome zooms these, but Safari apparently does not. I fixed it by setting the transformation origin where I wanted it using rem (which explicitly scale with text.) Ems might have worked as well, but I think rems are safer since this issue was caused by device zoom instead of page styles.

On release in the monolith, this will fix WR-246.

## :framed_picture: What does this change look like?

- [x] Follow the the [Guidelines for an optimal design ping](https://paper.dropbox.com/doc/Guidelines-for-Sharing-User-Facing-Changes-with-Design--BpL8hpJLMugy6033aT5m0JdaAg-bdKGQtYH9qO9I00hUkA6k) to add helpful screenshots/videos for design.
- [x] @ mention the design team on this PR to request approval on your changes. A designer will "thumbs up" react to your PR if they approve it, or will leave comments if it's not quite approved yet.

https://github.com/NoRedInk/noredink-ui/assets/355401/e58dc0d4-1a71-4fb2-835d-3b51aa28dba6

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
    - [x] Component docs include a changelog
    - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
    - [x] The Component Catalog is updated to use the newest version, if appropriate
    - [x] The Component Catalog example version number is updated, if appropriate
    - [x] Any new customizations are available from the Component Catalog
    - [x] The component example still has:
        - an accurate preview
        - valid sample code
        - correct keyboard behavior
        - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
    - e.g., as a dev, I can conveniently add an `nriDescription`
    - and adding a new feature to the component will _not_ require major API changes to the component
- [x] If this is a new major version of the component, our team has stories created to upgrade all instances of the old component. Here are links to the stories:
  - add your story links here OR just write this is not a new major version

### CODE REVIEW

**Comment by BrianHicks** [comment]
@staceyadams is the tiny adjustment here OK?

https://github.com/NoRedInk/noredink-ui/assets/355401/313e29b1-67d7-4d5c-9d25-71e9b5c8574a

(In a last Lindy's head shenanigan… what is love? Baby don't hurt me, don't hurt me, no more.)

**Review by ArthurJordao — APPROVED** [review]
css is my passion

**Comment by staceyadams** [comment]
> @staceyadams is the tiny adjustment here OK?
> 
>  Screen.Recording.2023-09-06.at.5.14.16.PM.mov 
> (In a last Lindy's head shenanigan… what is love? Baby don't hurt me, don't hurt me, no more.)

Please make this a Slack emoji 😂

**Comment by BrianHicks** [comment]
guessing the change is OK then? 😆

**Pull request merged**
