### PR TITLE
Elm-embedded assets for nri-ui

### PR DESCRIPTION
**Pull request by omnibs**
# Why

This should simplify using this package from the perspective of hosting assets.

Right now what happens is users must ensure they have the right assets to use these components, copy them over from here or from god knows where.

# What

The idea is have all assets in SVG and have them converted into Elm code.

0.19 dead code elimination helps users of the library not pay the cost for assets they don't use.

We can leave holes for external assets in `Icons` so folks can supply their own `ImgUrl` or `SvgSprite` assets. We at NRI can make use of those to ease the transition.

# How

I've written a small and dirty SVG to Elm converter that creates "extensible" SVGs we can add `Attribute`s and `Svg` child elements to (for alt text and other things).

I created an `Icons.V4` that removes all `Icon.someIcon` methods in favour of a union type, like we had in the `V1` days. Given we're pushing for embedded assets I think it was more appropriate.

# What's left over

* Making things use `Icons/V4.elm`, starting with the `Example/Icons.elm`
  - This looks like a lot of work
* Figuring out what `svgo` settings we want
  - `RemoveStyles` for instance is disabled rn, bc we have SVGs that are distinguished by color (bulb and hint)
* Figuring out if pngs converted into SVG are working properly everywhere
  - SVGs grow to fill the container and maybe we'll have problems with things that trust an icon will be a certain size bc it used to be a png
* Writing a friendly "How to add assets" like Luke wrote for the NRI Monolith.

### CODE REVIEW

**Comment by omnibs** [comment]
Another What's Left, but this one is a maybe:
* Move all `icon-builder` assets from the NRI Monolith

This is a list of what they are called in the `Icons.V3` functions, and what they are called in the Assets record, to help in finding them. The `asset.something` names map directly to the names of the svgs in the NRI Monolith.

```
activity -> assets.activity
assignmentTypeDiagnostic -> assets.diagnostic
assignmentTypePractice -> assets.practice
assignmentTypeQuiz -> assets.quiz
assignmentTypeWritingCycle -> assets.writingcycle
checkMarkSvg -> assets.checkmark
class -> assets.class
clever -> assets.clever
clock -> assets.clock
compassSvg -> assets.compass
customSvgSprite -> assets.asset
customImage -> assets.asset
document -> assets.document
download -> assets.download
edit -> assets.edit
editWriting -> assets.editWriting
exclamation -> assets.exclamation
flipper -> assets.flipper
footsteps -> assets.footsteps
gear -> assets.gear
guidedWrite -> assets.icons_guidedWrite_svg
key -> assets.key
leaderboard -> assets.leaderboard
lock -> assets.lock
newspaper -> assets.newspaper
openClose -> assets.openClose
performance -> assets.performance
preview -> assets.preview
seeMore -> assets.seemore
share -> assets.share
skip -> assets.skip
sort -> assets.sort
sortArrow -> assets.sortArrow
speedometer -> assets.speedometer
writingAssignment -> assets.writingAssignment
submitting -> assets.submitting
rating -> assets.rating
revising -> assets.revising
```

**Comment by tesk9** [comment]
Hi! We have a story in our backlog to add new assets. Should folks be aware of this PR as they start that work? If so, what changes are there to the previous process?

**Comment by omnibs** [comment]
@tesk9 I'm not sure if yall should use this.

I think there's 1+wk of work left to make noredink-ui elements on current versions only use svgs, and I know I can't spare the time now :<

This was a rabbit-hole I dug into while trying to make our assets work with Elm 0.19, but it turned out not being necessary.

**Comment by omnibs** [comment]
Going to close this PR, it's probably not useful anymore at this point

**Pull request closed without merging**
