### PR TITLE
Clickable text underline

### PR DESCRIPTION
**Pull request by bendansby**
Changes the clickable text hover style to be a bottom border rather than text-decoration

image

### CODE REVIEW

**Comment by bendansby** [comment]
>Why do we want to use a border instead of text decoration

Because it looks better! (to me :-)

**Comment by bendansby** [comment]
>Could you please add this change to the "post-release patch changes" section at the top of the doc?

Done!

**Comment by bendansby** [comment]
>I'm going to see if I can get a PR through to the monolith that'll protect us before this merges

Thank you!

**Comment by tesk9** [comment]
Made a PR here: https://github.com/NoRedInk/NoRedInk/pull/26334

**Pull request merged**
