### PR TITLE
Add count

### PR DESCRIPTION
**Pull request by tesk9**
Replaces:
- `Page.Teach.Facilitate.Benchmarks.New.Icon`'s `numeral`
- `Page.Curriculum.Views.LearningModuleIcon`'s `number`

I'm renaming to `count` unless anybody objects because I think it's clearer -- I thought the icon would be a one with a circle in it, when I first saw the names.

cc @NoRedInk/design

### CODE REVIEW

**Comment by bendansby** [comment]
Wait, if it's already being used in Modules what's this? https://github.com/NoRedInk/NoRedInk/pull/39483 @erik-nri @ap-nri

**Comment by tesk9** [comment]
It's used in [`viewRootFolderHeader`](https://github.com/NoRedInk/NoRedInk/blob/master/monolith/ui/src/Page/Curriculum/BrowseAndAssignLayout.elm#L1015)... 

(Not sure if this is already on your radar, but in looking at that code, I'm seeing casing on display copy, which is somewhat risky since the copy is highly likely to change over time, and folks who change the copy won't expect the icon and styles to change with it! I recommend a union type instead, or make these values configurable. LMK if you want to pair on it, and I can explain more what I mean)

**Review by asterite — APPROVED** [review]
Looks good!

**Comment by lindsaykwardell** [comment]
> It's used in [`viewRootFolderHeader`](https://github.com/NoRedInk/NoRedInk/blob/master/monolith/ui/src/Page/Curriculum/BrowseAndAssignLayout.elm#L1015)...
> 
> (Not sure if this is already on your radar, but in looking at that code, I'm seeing casing on display copy, which is somewhat risky since the copy is highly likely to change over time, and folks who change the copy won't expect the icon and styles to change with it! I recommend a union type instead, or make these values configurable. LMK if you want to pair on it, and I can explain more what I mean)

Completely agree on the display copy, however this is what was specced and requested. Once modules gets some time in production we'll probably revisit to improve this code.

**Comment by erik-nri** [comment]
@bendansby when I paired with alex on this we found the numeral use over in benchmarks and did not realize it was also implemented in LearningModules.

**Pull request merged**
