### PR TITLE
Add top left icon to containers

### PR DESCRIPTION
**Pull request by ap-nri**
# :wrench: Modifying a component

## Context

Please link to any relevant context and stories.

### Look at the shadow hewing to the ambit of the brain.
image

### More typical usage
image

@bendansby nota bene I upgraded `quickWriteCircled` and `guidedDraftCircled` to use a `<circle>` to draw a circle. PR that upgrades every circled icon TK. If you want the rendered SVG to update some master file it's

#### Quick Write
```svg
<svg viewBox="0 0 70 70" fill="currentcolor" aria-hidden="true" role="img" focusable="false">
  <g fill-rule="evenodd">
    <circle cx="35" cy="35" r="35"></circle>
    <g transform="translate(12.500000, 18.400000)" fill="#FFFFFF">
      <path d="M16.838,20.0521143 L14.338,22.5371143 L6.5,22.5379714 L6.5,20.0522571 L16.838,20.0521143 Z M21.339,15.5771143 L18.838,18.0631143 L2,18.0636857 L2,15.5779714 L21.339,15.5771143 Z M26.339,10.6061143 L23.838,13.0921143 L5.5,13.0922571 L5.5,10.6065429 L26.339,10.6061143 Z M31.338,5.63511429 L28.839,8.12011429 L1.0658141e-14,8.12082857 L1.0658141e-14,5.63511429 L31.338,5.63511429 Z"></path>
      <path d="M12.416,26.8879714 L17.62495,32.067156 L10.33395,34.1373086 L12.416,26.8879714 Z M34.625,4.85261143 L39.781,9.97914857 L19.158,30.4843029 L14.002,25.3577657 L34.625,4.85261143 Z M39.5785,3.62376795e-14 L44.7345,5.12653714 L41.27355,8.56771029 L36.11755,3.44117314 L39.5785,3.62376795e-14 Z"></path>
    </g>
  </g>
</svg>
```

#### Guided Draft

```html
<svg viewBox="0 0 70 70" fill="currentcolor" aria-hidden="true" role="img" focusable="false">
  <g fill-rule="evenodd">
    <circle cx="35" cy="35" r="35"></circle>
    <path d="M56.6059844,47.0760445 L48.4447276,29.1927202 C48.310599,28.8809029 48.044072,28.7014662 47.6869763,28.7014662 L38.0991385,28.7014662 C37.4755276,29.9051635 36.9842736,30.8858878 36.8954412,31.0200283 C36.4947855,31.8230878 35.6917439,32.3125581 34.8433763,32.3125581 C33.9514844,32.3125581 33.1484249,31.821304 32.7913114,31.0200283 L31.5876141,28.7014662 L21.9997763,28.7014662 C21.6879649,28.7014662 21.3761655,28.8791489 21.2420249,29.1927202 L13.0807686,47.0760445 C12.946637,47.3443078 12.9919273,47.6108229 13.1260589,47.879104 C13.2601907,48.102077 13.5267147,48.2362056 13.794978,48.2362056 L55.848126,48.2362056 C56.1163893,48.2362056 56.3829044,48.102077 56.5170449,47.879104 C56.6947276,47.656131 56.7400179,47.3443256 56.6058833,47.0760445 L56.6059844,47.0760445 Z M23.9631931,37.7566662 C23.4719331,37.7566662 23.0713012,37.3560105 23.0713012,36.8647743 C23.0713012,36.3735202 23.4719568,35.9728824 23.9631931,35.9728824 L24.4979714,35.9728824 C24.9892255,35.9728824 25.3898633,36.3735381 25.3898633,36.8647743 C25.3898633,37.3560283 24.9892076,37.7566662 24.4979714,37.7566662 L23.9631931,37.7566662 Z M28.0655331,41.4583743 C27.9766947,41.6813472 27.7537217,41.8590299 27.5307547,41.8590299 C27.4854644,41.8590299 27.396626,41.8590299 27.353072,41.8137397 C27.3077817,41.8137397 27.0412547,41.679611 26.9959644,41.679611 C26.1493866,41.3225035 25.4351595,40.7877191 24.9003812,40.0299678 C24.9003812,39.9846716 24.7226985,39.8069948 24.6774082,39.7616986 C24.4997255,39.4934353 24.5432736,39.1380878 24.8115368,38.9586391 C25.0798001,38.7809564 25.4351476,38.8245105 25.6145963,39.0927737 C25.6598866,39.138064 25.7487309,39.3157467 25.792279,39.3157467 C26.2382249,39.8958332 26.8183114,40.296471 27.4419222,40.6082764 C27.4872125,40.6082764 27.6648952,40.6971148 27.7101855,40.6971148 C28.0202547,40.8329916 28.1997033,41.1448029 28.0655509,41.4583445 L28.0655331,41.4583743 Z M33.1051682,41.3242397 C33.0598779,41.3695299 32.7933568,41.4583743 32.7933568,41.5019224 C32.169746,41.8137397 31.455519,41.9931764 30.6524595,42.0820089 C30.5183249,42.0820089 30.3841963,42.1272991 30.2518039,42.1272991 C30.2065136,42.1272991 29.8946963,42.1725953 29.8946963,42.1725953 C29.5828849,42.1725953 29.3146098,41.9496224 29.3146098,41.637817 C29.3146098,41.3259997 29.5375828,41.0577305 29.8493882,41.0577305 C29.8946785,41.0577305 30.3841666,41.0124343 30.472999,41.0124343 C31.1419179,40.9235959 31.7220044,40.7894613 32.2567828,40.5211802 C32.2567828,40.5211802 32.4797558,40.4323418 32.525046,40.3870516 C32.7933093,40.252917 33.1486568,40.3417613 33.2827974,40.6100245 C33.5057703,40.8329975 33.3716417,41.190111 33.1051147,41.3242516 L33.1051682,41.3242397 Z M36.7615682,37.0424451 C36.7162779,37.0877353 36.6274395,37.2654181 36.5838855,37.3107083 C36.4497568,37.5336813 36.2720741,37.8019683 36.1379395,38.0684656 C35.8696763,38.5144116 35.6031612,38.9603575 35.2913558,39.4063035 C35.2913558,39.4515878 35.1136731,39.6292764 35.0683828,39.6745608 C34.9342541,39.8086953 34.8001195,39.8975337 34.6224368,39.8975337 C34.4883082,39.8975337 34.3994639,39.8522494 34.2653352,39.7634051 C33.997072,39.5857224 33.9535179,39.2286267 34.1764909,38.9603456 C34.2217812,38.9150553 34.3541736,38.7373726 34.3541736,38.7373726 C34.6224368,38.336717 34.888952,37.8907889 35.1572331,37.4883672 C35.2913676,37.220104 35.4690503,36.9535889 35.6484871,36.7306159 C35.6484871,36.6853256 35.7826217,36.5076429 35.8261698,36.4623526 C36.0038525,36.1940894 36.3609482,36.1505413 36.6292293,36.3282181 C36.8504601,36.4187986 36.9392985,36.7759062 36.7616217,37.0424451 L36.7615682,37.0424451 Z M40.9092222,34.9921224 L40.5974109,34.9921224 C40.2855936,34.9921224 39.9738001,35.0374126 39.6602109,35.0809608 C39.2142649,35.126251 38.8571514,35.2586494 38.5000379,35.4380683 C38.5000379,35.4380683 38.2770649,35.5269067 38.2770649,35.572197 C38.1882206,35.6174932 38.0993822,35.6610413 38.0088017,35.6610413 C37.831119,35.6610413 37.608146,35.572197 37.5175476,35.3927781 C37.3398649,35.1245148 37.4722574,34.7691672 37.7405206,34.6350267 C37.7858109,34.5897364 38.052332,34.457344 38.052332,34.457344 C38.4982779,34.234371 38.989532,34.1002364 39.5678347,34.0113981 C39.9249422,33.9661078 40.2820617,33.9225537 40.6373914,33.9225537 L40.994499,33.9225537 C41.3063103,33.9225537 41.5745855,34.1908229 41.5745855,34.5026462 C41.4874833,34.723871 41.2209622,34.9921581 40.9091449,34.9921581 L40.9092222,34.9921224 Z M43.0048114,35.3927781 C42.7365482,35.2586494 42.6041558,34.901524 42.7365482,34.6350267 C42.8706828,34.3667635 43.2278022,34.234371 43.4942995,34.3667635 C43.5395898,34.4120537 43.8061168,34.5008921 43.8061168,34.5444462 C44.9209817,35.168057 45.5010682,36.0164245 45.7240412,36.4623705 C45.7240412,36.5076608 45.8581698,36.7741818 45.8581698,36.7741818 C45.9470141,37.0859991 45.8128795,37.3977926 45.5010682,37.4884089 C45.455772,37.5336991 45.3669336,37.5336991 45.3233855,37.5336991 C45.1004125,37.5336991 44.8774395,37.3995705 44.7886071,37.1765975 C44.7886071,37.1765975 44.6997628,37.0424629 44.6997628,36.9989148 C44.5220801,36.6418072 44.1196763,36.0181905 43.2277844,35.5722445 C43.2277844,35.5269543 43.0483655,35.3928197 43.0048114,35.3928197 L43.0048114,35.3927781 Z M47.1959898,41.4130483 C47.0618612,41.547177 46.9277266,41.590731 46.7500439,41.590731 C46.6159152,41.590731 46.4817806,41.5454408 46.3493882,41.4565964 L45.6351612,40.7876775 L45.0550747,41.5019045 C44.9209401,41.6360391 44.7868114,41.7248775 44.6091287,41.7248775 C44.4749941,41.7248775 44.3408655,41.6795872 44.2520212,41.5907489 C44.0290482,41.3677759 43.9837639,41.0106624 44.1631828,40.7876894 L44.7867936,40.0299381 L44.1178747,39.4063272 C43.8949017,39.1833543 43.8496114,38.8262408 44.0725844,38.6032678 C44.2955574,38.3802948 44.6526709,38.3350045 44.8756439,38.5579775 L45.4992547,39.138064 L46.0793412,38.423837 C46.3023141,38.200864 46.6594276,38.1555737 46.8824006,38.3349926 C47.1053736,38.5579656 47.1506639,38.9150791 46.9712449,39.1380521 L46.3476341,39.8958035 L47.1053855,40.5647224 C47.418939,40.7894435 47.418939,41.1448089 47.195966,41.4130483 L47.1959898,41.4130483 Z" fill="#FFFFFF"></path><path d="M34.2199439,30.3530716 C34.4882071,30.8443256 35.2006682,30.8443256 35.4236412,30.3530716 C35.4236412,30.3530716 38.2769817,24.7787472 38.9459006,23.4409094 C39.6148195,22.1483797 39.6148195,20.6310932 38.9459006,19.2932553 C37.7857276,17.0182175 35.0212195,16.0828013 32.7481439,17.2411905 C30.473106,18.4013635 29.5812141,21.254704 30.696079,23.4389472 C31.8109439,25.6268472 34.2200747,30.3528932 34.2200747,30.3528932 L34.2199439,30.3530716 Z M34.8435547,18.9377472 C36.1813925,18.9377472 37.2509493,20.007304 37.2509493,21.3451418 C37.2509493,22.6829797 36.1813925,23.7525364 34.8435547,23.7525364 C33.5057168,23.7525364 32.4361601,22.6829797 32.4361601,21.3451418 C32.4361601,20.0526121 33.5057168,18.9377472 34.8435547,18.9377472 Z" fill="#FFFFFF"></path>
  </g>
</svg>
```

- If there are user facing changes, you will be asked later to add a designer as a reviewer. Please fill in this section by following [the guidelines for an optimal design review](https://paper.dropbox.com/doc/Guidelines-for-Sharing-User-Facing-Changes-with-Design--BpL8hpJLMugy6033aT5m0JdaAg-bdKGQtYH9qO9I00hUkA6k).
- If there are not user facing changes, include any screenshots or videos that would be helpful to reviewers.

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
  - [x] Component docs include a changelog
  - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
  - [x] The Component Catalog is updated to use the newest version, if appropriate
  - [x] The Component Catalog example version number is updated, if appropriate
  - [x] Any new customizations are available from the Component Catalog
  - [x] The component example still has:
    - an accurate preview
    - valid sample code
    - correct keyboard behavior
    - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
  - e.g., as a dev, I can conveniently add an `nriDescription`
  - and adding a new feature to the component will _not_ require major API changes to the component
- ~[ ] If this is a new major version of the component, our team has stories created to upgrade all instances of the old component. Here are links to the stories:~
  - This is not a new major version
- [x] Please assign the following reviewers (applicable Sep 2023–Dec 2023):
  - [x] [a11y-volunteer-reviewers](https://github.com/orgs/NoRedInk/teams/volunteer-a11y-reviewers) - Someone from this group will review your PR in full.
  - [x]  [team-accessibilibats-a11ybats](https://github.com/orgs/NoRedInk/teams/team-accessibilibats-a11ybats) - Someone from this group will review your PR for ACCESSIBILITY ONLY.
  - [x]  Someone from your team who can review requirements from your team's perspective. (This could be the same person from the [a11y-volunteer-reviewers](https://github.com/orgs/NoRedInk/teams/volunteer-a11y-reviewers) group if you'd like.)
  - [x]  If there are user-facing changes, a designer. (You may want to direct your designer to the [deploy preview](https://github.com/NoRedInk/noredink-ui#reviews--preview-environments) for easy review):
    - For writing-related component changes, add Stacey (staceyadams)
    - For quiz engine-related components, add Ravi (ravi-morbia)
    - For a11y-related changes to general components, add Ben (bendansby)
    - For general component-related changes or if you’re not sure about something, add the Design group (NoRedInk/design)

### CODE REVIEW

**Comment by ap-nri** [comment]
@ravi-morbia you can futz with it at https://deploy-preview-1571--noredink-ui.netlify.app/#/doodad/Container

**Comment by bendansby** [comment]
Why are we making this part of the container component?

**Comment by ap-nri** [comment]
@bendansby @ravi-morbia Why indeed. So I've gotten pushback in general for creating design elements without adding them to the library. Looking in my crystal ball, it seemed like this was a pattern we might want more of since it made it into a design for this time around. Since the shadows were pretty tricky to get right, it made sense to me to put it in here so that we don't have some of these with and some without shadows. 

If i've misread it and this is only going to happen on this one (well two if we do weekly GDs) element on one page then np, the change can live entirely in the app.

**Comment by bendansby** [comment]
The containers are basically just styles, so we don't want to complicate them with page-specific content. I'd put this in the app instead 👍

**Comment by ravi-morbia** [comment]
Thanks @ap-nri, I understand where you're coming from.

But in this case I think it will just be this 1 instance with the weekly QW. GD is a very different beast, so we moved away from putting it on the dashboard for now. And if we did in the future, it would be something different as GD's are much more involved assignments that are infrequently given by teachers.

I think it makes more sense for this to be in the app.

**Comment by ap-nri** [comment]
ten four good buddies

**Comment by ap-nri** [comment]
pls don't delete the branch yet as I'll need it for the frontend code

**Pull request closed without merging**
