### PR TITLE
add a basic Buck2 project layout

### PR DESCRIPTION
**Pull request by BrianHicks**
Adds a new CI target that uses Buck to build the repo. It doesn't actually do anything yet, but this sets the stage!

This PR has a *ton* of files, but that's just due to pulling in `prelude` as a vendored directory.

### CODE REVIEW

**Comment by BrianHicks** [comment]
whoops, excuse me folks: I meant to tag the writing experience team!

**Comment by BrianHicks** [comment]
ah, but we haven't added that team to the repo! That's what happened!

**Comment by BrianHicks** [comment]
oh, no, it's just that we have too many people on that team. Well, trying again.

**Review by juanedi — APPROVED** [review]
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Pull request merged**
