### PR TITLE
Added html function to QuestionBox

### PR DESCRIPTION
**Pull request by nunocf**
# :wrench: Modifying a component

## Context

[PHX-1151](https://linear.app/noredink/issue/PHX-1151/support-passing-html-to-noredink-ui-questionbox) requires us to add a html function to the QuestionBox to allow us to render DisplayElements within the question box.

## :framed_picture: What does this change look like?
Here's a screenshot of the component catalogue using the new `html` function
image
## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
  - [x] Component docs include a changelog
  - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
  - [x] The Component Catalog is updated to use the newest version, if appropriate
  - [x] The Component Catalog example version number is updated, if appropriate
  - [x] Any new customizations are available from the Component Catalog
  - [x] The component example still has:
    - an accurate preview
    - valid sample code
    - correct keyboard behavior
    - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
  - e.g., as a dev, I can conveniently add an `nriDescription`
  - and adding a new feature to the component will _not_ require major API changes to the component
- [x] If this is a new major version of the component, our team has stories created to upgrade all instances of the old component. Here are links to the stories:
  - add your story links here OR just write this is not a new major version
- [x] Please assign the following reviewers (applicable Sep 2023–Dec 2023):
  - [x] [a11y-volunteer-reviewers](https://github.com/orgs/NoRedInk/teams/volunteer-a11y-reviewers) - Someone from this group will review your PR in full.
  - [x]  [team-accessibilibats-a11ybats](https://github.com/orgs/NoRedInk/teams/team-accessibilibats-a11ybats) - Someone from this group will review your PR for ACCESSIBILITY ONLY.
  - [x]  Someone from your team who can review requirements from your team's perspective. (This could be the same person from the [a11y-volunteer-reviewers](https://github.com/orgs/NoRedInk/teams/volunteer-a11y-reviewers) group if you'd like.)
  - [x]  If there are user-facing changes, a designer:
    - For writing-related component changes, add Stacey (staceyadams)
    - For quiz engine-related components, add Ravi (ravi-morbia)
    - For a11y-related changes to general components, add Ben (bendansby)
    - For general component-related changes or if you’re not sure about something, add the Design group (NoRedInk/design)

### CODE REVIEW

**Review by micahhahn — CHANGES_REQUESTED** [review]
The code generation for the markdown is not right... (it should be `QuestionBox.markdown` instead of `content`).

image

**Comment by ravi-morbia** [comment]
@nunocf the spacing for the text elements inside seem to be different between markdown and html.
Can we match the html spacing to be the same as markdown?
Also are display elements part of this PR, or is this a separate, pre-work ticket for adding display elements to the QuestionBox?

**Comment by micahhahn** [comment]
> Also are display elements part of this PR, or is this a separate, pre-work ticket for adding display elements to the QuestionBox? 

This is pre-work! We will be rendering the display elements in a different place, and then handing off the HTML directly to the QuestionBox component

**Comment by nunocf** [comment]
@ravi-morbia 

> Can we match the html spacing to be the same as markdown?
Do you mean for the example or in general?
The container accepts any kind of html, with its own CSS. I can change the CSS to match the markdown example but it would only be useful for this example page so I feel it is unnecessary, but I can change it if you think it will help!

**Comment by ravi-morbia** [comment]
Hey @nunocf I meant for all instances when html is being used. So there is no way for us to control the spacing between paragraphs with html, is that right?

**Review by charbelrami — APPROVED** [review]
Looks good from a11y perspective!

**Comment by nunocf** [comment]
@ravi-morbia We can force some styles, but whoever is calling this new function will most likely be adding styles to it, so I think us allowing the default CSS styles defined globally make the behavior more predictable.

My opinion is that we shouldn't override styling because of the above.

**Comment by ravi-morbia** [comment]
Gotcha, so to confirm, when we use html from the other side in QuestionBox, we will be able to define spacing, correct? I think that's fine then.

The only reason I would say it might be better to override here is because we have defined spacing for paragraph text and bullet points. So it seems like it would keep consistency better to define it here. But maybe I am missing something.

In any case, thanks for discussing. I'll go ahead and approve.

**Review by ravi-morbia — APPROVED** [review]

**Pull request merged**
