### PR TITLE
ask Bors to check the tests

### PR DESCRIPTION
**Pull request by BrianHicks**
This sets up Bors, which will automatically merge PRs that pass all the checks. It works like Homu did, but batches PRs into bigger groups for efficiency's sake.

Once this merges, you can talk to it the same way we do @NoRedInkBot in the monorepo, except we call it "duet" instead (for now... we just don't want to cause a conflict with two merge robots running on the same triggers!) So for example, `duet r+` will add the PR to the merge batch, `duet r-` will remove it, et cetera.

Fixes FXN-1289

### CODE REVIEW

**Comment by BrianHicks** [comment]
requesting @NoRedInk/team-accessibilibats-a11ybats since you own this repo! But it's really more of an FYI since we already talked on Slack.

**Review by caiquefigueiredo — APPROVED** [review]

**Comment by BrianHicks** [comment]
I just wanna see what this'll do without a `bors.toml` in master…

duet r=caiquefigueiredo

**Comment by BrianHicks** [comment]
huhhh, apparently it didn't need it? Or maybe it used this branch? 🤷

**Pull request merged**
