### PR TITLE
:wrench: Improving hover behavior for Highlighter

### PR DESCRIPTION
**Pull request by tesk9**
## Context

Fixes A11-2534

When hovering part of a highlight, the entire highlight should change styles, not just the word you're highlighting.

For overlapping highlights, when you hover a word that appears in multiple highlights, the shortest highlight should show hover styles.

## :framed_picture: What does this change look like?

Screen Shot 2023-04-06 at 2 01 56 PM

This screenshot shows 2 overlapping highlights, the second of which has one word highlighted. 

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
    - [x] Component docs include a changelog
    - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
    - [x] The Component Catalog is updated to use the newest version, if appropriate
    - [x] The Component Catalog example version number is updated, if appropriate
    - [x] Any new customizations are available from the Component Catalog
    - [x] The component example still has:
        - an accurate preview
        - valid sample code
        - correct keyboard behavior
        - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
    - e.g., as a dev, I can conveniently add an `nriDescription`
    - and adding a new feature to the component will _not_ require major API changes to the component

### CODE REVIEW

**Comment by charbelrami** [comment]
Hover is inconsistent with selection

https://user-images.githubusercontent.com/5647344/230626380-235d9cae-f0f9-4821-8456-d7b69fc08af8.mov

https://user-images.githubusercontent.com/5647344/230626401-fccfc46f-50c5-4bac-a542-633818196f19.mov

It is not possible do remove selection. Is this expected?

https://user-images.githubusercontent.com/5647344/230626423-5f1dad3c-80de-44b0-9973-eba86597af85.mov

**Comment by tesk9** [comment]
Eek good catch on the hover styles for non-overlapping! Sorry about that 🙈 

For the second question, yes, it's expected that highlights aren't removable for the overlapping highlights example. (Otherwise, it's not possible to _create_ an overlap, and this mirrors how the inline commenting code works)

**Comment by tesk9** [comment]
@charbelrami should be fixed!

**Comment by charbelrami** [comment]
Overlapping only changes styles when I highlight one overlapping word, but not when I highlight more words.

https://user-images.githubusercontent.com/5647344/230960696-2fa5b987-e94a-4d0e-b051-c2a7dcb30c68.mov

**Comment by tesk9** [comment]
@charbelrami I'm not sure I understand what the problem is! This:

https://user-images.githubusercontent.com/8811312/231008914-36506e98-9fa5-48b7-9d44-b6c738f3c663.mov


Looks correct to me?

**Review by charbelrami — APPROVED** [review]
Thank you! Looks great!!

**Pull request merged**
