### PR TITLE
Specific page titles

### PR DESCRIPTION
**Pull request by tesk9**
Provide specific page titles for every route in the styleguide, implementing [Technique H25](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/H25) for [Success Criterion 2.4.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html).

### CODE REVIEW

**Review by BrianHicks — COMMENTED** [review]
Code looks fine! "X in the NoRedInk Style Guide" seems really unusual though so I did some digging. https://accessibility.iu.edu/creating-content/web-content/titles.html has some good stuff, but the *most* interesting thing to me about that page is how they do their own titles. It looks like they're breadcrumbs, basically. I think it might be good to use that approach!

- `example.name ++ ": Examples: NoRedInk Style Guide"`
- `"Not Found: NoRedInk Style Guide"`
- `Category.forDisplay category ++ ": Category: NoRedInk Style Guide"`
- `"NoRedInk Style Guide"`

Overall that seems nice! Although I note the use of `:` as fairly unusual. I wonder if ` | ` as a separator would be acceptable to a screen reader. Looks like GitHub uses a &middot; (`\u00B7` I think?) and I assume they've done at least some research on what's best in a technical context.

**Comment by BrianHicks** [comment]
wow, middot has a homepage https://middot.net/

**Comment by tesk9** [comment]
For the Englishy page titles, I was following the suggestions in [the first stackoverflow answer here](https://stackoverflow.com/questions/24208808/accessibility-html-title-tag-separators-alternatives-to-the-vertical-line-p).

I think the `|` character will be understood by screenreader users, but for me anyway (as a very beginner user) it's kind of annoying/confusing, as VO reads it as "vertical line". 

Compare:

https://user-images.githubusercontent.com/8811312/160916145-b4cada64-e254-4236-ad10-c7da859f2886.mov

https://user-images.githubusercontent.com/8811312/160916131-c2cbacb5-de01-49b8-ada4-9e7793ca6ffa.mov

Does this change your opinion on using the character separator versus English connecting words? I will change it if you prefer the pipe or the colon

**Comment by BrianHicks** [comment]
ah, bah, and it says "middle dot" for &middot;. I think probably colons or english make most sense, given that.

**Comment by BrianHicks** [comment]
oh hey, some experimentation reveals hyphen as being maybe nice. It creates a clear visual hierarchy and voiceover pronounces it as a slightly longer gap between words.

**Comment by tesk9** [comment]
> I think probably colons or english make most sense, given that.

Sounds good! I vagueeeelly prefer English, if that's alright?

**Review by BrianHicks — APPROVED** [review]

**Comment by BrianHicks** [comment]
Yeah, totally great! Sorry if I’m coming off as pedantic—I’m just excited by the possibilities 😅

**Pull request merged**
