### PR TITLE
correct instructions for testing individual components

### PR DESCRIPTION
**Pull request by BrianHicks**
This just updates some instructions that were wrong after a recent change. Tiny!

### CODE REVIEW

**Review by tesk9 — COMMENTED** [review]
Just to clarify, now the only way to run the tests locally without percy is to not have the percy credentials set up locally?

**Comment by BrianHicks** [comment]
Oh, is that a thing that's causing you problems? Is that common on Accessibilibats? You could probably run `env -u PERCY_TOKEN script/puppeteer-test.sh` to avoid sending screenshots to Percy.

**Comment by tesk9** [comment]
Not causing me problems as such! Just wanted to be sure I understood the change/intent of the change.

**Review by tesk9 — APPROVED** [review]
Thanks for updating!

**Pull request merged**
