### PR TITLE
Remove external link Add tts capabilities to question box - phx-465, Fix markdown parsing on button, add noredink-ui policies & contribution guidelines 

### PR DESCRIPTION
**Pull request by ArthurJordao**
Included on this version:
Add tts capabilities to question box - phx-465 #1249 
Fix markdown parsing on button #1247 
add noredink-ui policies & contribution guidelines #1246

### CODE REVIEW

**Review by tesk9 — COMMENTED** [review]
@ArthurJordao I think some of those changes you mentioned are actually already published! When I look at https://github.com/NoRedInk/noredink-ui/compare/21.13.2...master, I see a markdown change in Button, your TTS changes, and readme improvements.

Bump looks good though! Would you like to pair on the actual release or do you know how to do it already?

**Comment by ArthurJordao** [comment]
@tesk9 wow, I didn't notice that, I looked for the last PR that was bumping the version and I didn't find those changes there https://github.com/NoRedInk/noredink-ui/pull/1245
Isn't there a PR for each bump? 🤔 

Or should I always look at the difference between the tag and master?

> Bump looks good though! Would you like to pair on the actual release or do you know how to do it already?
I saw the instructions on the readme and seen simple to me, but if I found some challenge I will send you a message!

**Comment by tesk9** [comment]
There _should_ be a PR for each bump, but since we don't currently have master locked against pushes, there's no _guarantee_ that there's a PR for each bump. I always look at the tags, just to be sure, but usually what you did will be right! (I might adjust the settings on the repo to enforce no-pushes-to-master, actually, to avoid this!)

**Review by tesk9 — APPROVED** [review]
🎉

**Comment by ArthurJordao** [comment]
> I might adjust the settings on the repo to enforce no-pushes-to-master, actually, to avoid this!)

Enforce no-pushes-to-master seems great!

**Pull request merged**
