### PR TITLE
Tessa/add self review icons

### PR DESCRIPTION
**Pull request by tesk9**
Adds highlighter, tada, microscope, and scale icons.

Screen Shot 2022-01-25 at 1 26 21 PM
Screen Shot 2022-01-25 at 1 26 15 PM
Screen Shot 2022-01-25 at 1 26 11 PM

### CODE REVIEW

**Review by micahhahn — COMMENTED** [review]
I assume the plan is to remove the definitions from ./Page/Learn/SelfReviews/Revise/StepIcon.elm after this has merged?

**Comment by tesk9** [comment]
Right!

**Comment by micahhahn** [comment]
> Right!

Great!

**Review by micahhahn — APPROVED** [review]
👍 

Image

**Comment by micahhahn** [comment]
@NoRedInkBot r+

**Comment by micahhahn** [comment]
Oh, I am the bot.

**Pull request merged**
