### PR TITLE
🔧 Adds stars to confetti

### PR DESCRIPTION
**Pull request by tesk9**
Not issued, just had an impulse after watching an internal presentation.

### Before

https://github.com/NoRedInk/noredink-ui/assets/8811312/88c95019-324d-476f-ba2e-5e438e48bd79

### After

https://github.com/NoRedInk/noredink-ui/assets/8811312/3c72f351-e67a-4676-a7ed-b35edbfa7baf

@NoRedInk/design what do you all think? Good idea?

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
    - [x] Component docs include a changelog
    - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
    - [x] The Component Catalog is updated to use the newest version, if appropriate
    - [x] The Component Catalog example version number is updated, if appropriate
    - [x] Any new customizations are available from the Component Catalog
    - [x] The component example still has:
        - an accurate preview
        - valid sample code
        - correct keyboard behavior
        - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
    - e.g., as a dev, I can conveniently add an `nriDescription`
    - and adding a new feature to the component will _not_ require major API changes to the component
- [x] If this is a new major version of the component, our team has stories created to upgrade all instances of the old component. Here are links to the stories:
  - not a new major version

### CODE REVIEW

**Comment by bendansby** [comment]
Still too skimpy either way to move me to celebration

**Comment by tesk9** [comment]
Should we add more elements? I think there are 200 at the moment. Bet we could add more!

**Comment by staceyadams** [comment]
I think that in general, confetti on websites doesn't feel celebratory anymore. I'm pro adding stars and merging this PR though!

**Review by charbelrami — APPROVED** [review]
Cool!

**Pull request merged**
