### PR TITLE
:wrench: supporting different width behaviors for breakpoints

### PR DESCRIPTION
**Pull request by tesk9**
Fixes A11-2309

## Context

The goal is to be able to specify how the Menu trigger width should behave at different breakpoints, so that we don't have nice-looking desktop views and janky-looking mobile views. See https://github.com/NoRedInk/noredink-ui/issues/1265 for some example screenshots.

Since Menu now integrates directly with Button and the other clickables, I'm addressing this need by adding per-viewport width support to Button. 

I don't think we'll want clickable texts to expand to take up tons of horizontal space, so I'm not making changes the ClickableText component.

I also think the width behavior of clickable svgs is a _bit_ less complicated? And it makes sense to let the user use mobileCss directly. Example of doing this is here: https://github.com/NoRedInk/NoRedInk/pull/42777.

Additionally, I wanted the width behavior to be easy to test and observe, so I split out an interactive example from the Button table, and made the Button table entirely non-interactive.

### Width behavior by breakpoint demo

https://user-images.githubusercontent.com/8811312/220441598-81b384b2-7534-412e-bc84-3f9512d822fe.mov

### Examples Table Before

image

### Examples Table After

image

cc @NoRedInk/design 

## Component completion checklist

- [x] I've gone through the relevant sections of the [Development Accessibility guide](https://paper.dropbox.com/doc/Accessibility-guide-4-Development--BiIVdijSaoijjOuhz3iTCJJ1Ag-rGoHpC91pFg3zTrYpvOCQ) with the changes I made to this component in mind
- [x] Changes are clearly documented
    - [x] Component docs include a changelog
    - [x] Any new exposed functions or properties have docs
- [x] Changes extend to the Component Catalog
    - [x] The Component Catalog is updated to use the newest version, if appropriate
    - [x] The Component Catalog example version number is updated, if appropriate
    - [x] Any new customizations are available from the Component Catalog
    - [x] The component example still has:
        - an accurate preview
        - valid sample code
        - correct keyboard behavior
        - correct and comprehensive guidance around how to use the component
- [x] Changes to the component are tested/the new version of the component is tested
- [x] Component API follows standard patterns in noredink-ui
    - e.g., as a dev, I can conveniently add an `nriDescription`
    - and adding a new feature to the component will _not_ require major API changes to the comopnent

### CODE REVIEW

**Comment by bendansby** [comment]
What if we want to use defaulTrigger for Menus, which we generally will?

**Comment by tesk9** [comment]
`defaultTrigger` uses `Button` under the hood, so you can pass a list of `Button` attributes when you make it!

**Comment by bendansby** [comment]
Awesome, thanks for doing this!

**Review by charbelrami — APPROVED** [review]
Looks great!

**Pull request merged**
