### PR TITLE
all text inputs should be 45px minimum

### PR DESCRIPTION
**Pull request by BrianHicks**
fulfilling the prophecy of Ben Dansby

image

### CODE REVIEW

**Comment by BrianHicks** [comment]
@bendansby yea / nay?

**Comment by bendansby** [comment]
Input or area?

**Comment by bendansby** [comment]
didn't mean to close

**Comment by BrianHicks** [comment]
looks like this affects both. Is that OK?

**Comment by BrianHicks** [comment]
image

**Comment by BrianHicks** [comment]
image

**Comment by bendansby** [comment]
Should be, as long as there aren't any actual visual changes to text inputs. At a glance looks good in the screenshot, though.

**Comment by BrianHicks** [comment]
cool, thanks. I'll make a note about asking for QA to check all the relevant places when adding it to the main repo.

**Pull request merged**
