### PR TITLE
update nixpkgs and switch to niv

### PR DESCRIPTION
**Pull request by BrianHicks**
This PR switches us to `niv` to manage nix dependencies. It also adds docs!

### CODE REVIEW

**Comment by BrianHicks** [comment]
@Arkham hey Ju, please LMK if you don't use Nix for this and I will find someone else to review. Teambot just suggested you 😄

**Comment by Arkham** [comment]
I'll try to set it up, can't think of a better test :)

**Comment by BrianHicks** [comment]
good idea ❤️

**Comment by BrianHicks** [comment]
It’s because nix is still not the only way to do it. Thanks for reviewing!

**Pull request merged**
