### PR TITLE
Bat/segmented control

### PR DESCRIPTION
**Pull request by tesk9**
Add a missing preview img to the card:
image

Add some example code to the segmented control example

### CODE REVIEW

**Review by micahhahn — APPROVED** [review]
👍

**Comment by micahhahn** [comment]
Somehow this broke CI tests after showing up green here after I merged?!?

https://github.com/NoRedInk/noredink-ui/runs/5744989070?check_suite_focus=true

Looks like just a field is missing in an object

**Comment by micahhahn** [comment]
@tesk9

**Comment by tesk9** [comment]
Fixed! This is what happens when you don't have a merge queue and don't run tests with latest master merged in. As annoying as homu is, it's very helpful to have it.

**Pull request merged**
