### PR TITLE
Kraken/clickable svg with border

### PR DESCRIPTION
**Pull request by tesk9**
for clickable svgs:
- adds withBorder setting 
- adds primary, secondary, and danger themes

Screen Shot 2020-09-28 at 12 28 28 PM

Questions:
- "secondary" is currently the navy color -- is that what secondary should mean here?
- do we want background color changes on hover?

### CODE REVIEW

**Comment by bendansby** [comment]
Woo-hoo! I think primary and secondary could match the corresponding button styles, so white icon on azure button and azure icon on white button with azure border.

Maybe a px or two more of padding? The eye icon looks good as is but some of the other icons look a little big within their confines.

**Comment by tesk9** [comment]
@bendansby sounds good! I wonder about the `danger` behavior then -- if we're matching the `Button` behavior, the interior would be red rather than white. Maybe `dangerInverted`? Or something like that...?

**Comment by bendansby** [comment]
Yup, that makes sense. We originally had a "danger secondary" button style in Sketch but it never ended up getting used.

**Comment by tesk9** [comment]
Oh I like `dangerSecondary` 👍 thanks!

**Comment by tesk9** [comment]
Screen Shot 2020-09-28 at 2 58 11 PM

Is redLight okay for the hover?

**Comment by bendansby** [comment]
Yup! Love the grid!

**Review by allymcknight — COMMENTED** [review]
Noice

**Review by allymcknight — APPROVED** [review]

**Pull request merged**
