### PR TITLE
Remove border

### PR DESCRIPTION
**Pull request by tesk9**
Fixes https://github.com/NoRedInk/NoRedInk/pull/29549#issuecomment-694251047

### CODE REVIEW

**Comment by tesk9** [comment]
I think the issue with the build is https://elmlang.slack.com/archives/C0HJVT881/p1600328127020100, which I believe should be handled separately

**Review by juanedi — APPROVED** [review]

**Comment by krinhorn** [comment]
@tesk9 I just found the same border on clicking the stuck status tooltip: 
image

**Comment by tesk9** [comment]
I don't think this code has been released yet -- looks like the last release tag is from 11 days ago https://github.com/NoRedInk/noredink-ui/releases/tag/12.4.0

That should get fixed when this is released. I'll do a release today!

**Comment by krinhorn** [comment]
oooo, sorry! definitely no rush, just my confusion around seeing this PR merged and not noticing the repo it was in.

**Pull request merged**
