### PR TITLE
Bat/new icons hurrah

### PR DESCRIPTION
**Pull request by tesk9**
Fixes https://github.com/NoRedInk/noredink-ui/issues/916

Screen Shot 2022-04-20 at 1 58 32 PM
Screen Shot 2022-04-20 at 1 58 25 PM

@NoRedInk/design Look good to you? I'm so used to the glowing bulb. Looks like it got a real close buzzcut 😆

### CODE REVIEW

**Comment by bendansby** [comment]
looks good!

**Comment by staceyadams** [comment]
I'm so used to it in yellow that the gray is throwing me off. I'm seeing a hot air balloon now. (but also I'm running on very few hours of sleep)

Without the rays, it matches up better to the size/weight of our other icons.

**Comment by tesk9** [comment]
Oh actually -- could you all double-check the Percy diff too? the default Message component looks pretty different without the rays

**Comment by tesk9** [comment]
(not sure if you got notified again, sorry if this is a double-ping -- @NoRedInk/design )

**Comment by staceyadams** [comment]
I don't think I've used Percy after they merged with browserstack. Who do I go to for access?

image

**Comment by tesk9** [comment]
Following up in slack re Percy!

You can [preview the Message component here](https://deploy-preview-917--noredink-ui.netlify.app/#/doodad/Message)

The [published version is here ](https://noredink-ui.netlify.app/#/doodad/Message)

**Comment by staceyadams** [comment]
I totally see buzzcut/ hot air balloon! I think it's fine though and will just take adjusting to.

As long as it's not this style of bulb, we're probably 👌 

image
image

**Comment by tesk9** [comment]
Awesome, thanks!

**Pull request merged**
