### PR TITLE
Tessa/update premium checkbox

### PR DESCRIPTION
**Pull request by tesk9**
Update the premium checkbox code to not depend on Assets.

### CODE REVIEW

**Comment by tesk9** [comment]
Ping, @brookeangel  :)

**Comment by brookeangel** [comment]
Oops, sorry! Lost track of this during retreat but will get to it tomorrow!

**Comment by brookeangel** [comment]
Screen Shot 2019-06-12 at 10 24 50 AM

When I build the styleguide locally, this is what I see - do you see the same?

**Comment by brookeangel** [comment]
Screen Shot 2019-06-12 at 10 24 32 AM

Also, unrelated... but do all the white checks appear yellow for you, or is my styleguide just displaying weirdly?

**Comment by brookeangel** [comment]
Hey @tesk9 - the code looks good, was confused by viewing the styleguide however!

**Comment by tesk9** [comment]
Thanks Brooke! great catch on the checkmark -- class name collision in the svgs, which I'm fixing on this branch.

I hadn't checked that the checkbox looked nice in firefox and apparently it looks like there's a gigantic p next to it there. Fixing!

**Comment by tesk9** [comment]
Screen Shot 2019-06-12 at 6 12 30 PM
Screen Shot 2019-06-12 at 6 12 22 PM

**Comment by brookeangel** [comment]
Not sure if you pushed the changes, @tesk9 !

**Comment by tesk9** [comment]
🤦‍♀ 

Thanks!

**Pull request merged**
