### PR TITLE
Fab/menu

### PR DESCRIPTION
**Pull request by tesk9**
keyboard

Ugh did I ever struggle to get the keyboard focus behavior to work! 😖 I don't know why this kind of thing is so hard! come on brain, go go go! 🌀 

At any rate... Here is a new version of Nri.Menu, for testing in Fab Friday!

### CODE REVIEW

**Comment by tesk9** [comment]
Hey, @BrianHicks ! This is a PR that comes out of a review we did in FAB Friday of how a menu is supposed to work. Let me know if you want to pair on reviewing, or talk through anything. And also -- feel free to assign this to another reviewer! Alex & Richard are regular FAB Friday attendees. (I assigned to Raven because AoO, but I'm not sure how real that is 😅)

**Comment by BrianHicks** [comment]
I don't think the AoO here is super real. This library is kind of a do-ocracy—if you want to improve it, you get to improve it! I'm gonna remove my review here since I don't think I'd be able to add anything on top of FAB's input.

**Comment by BrianHicks** [comment]
(but if you'd like me specifically to look at it for non-AoO reasons, please just LMK)

**Review by ap-nri — APPROVED** [review]
@NoRedInkBot r+

**Pull request merged**
