### PR TITLE
Bat/confetti sample code

### PR DESCRIPTION
**Pull request by tesk9**
Adds example code to the Confetti example.

Fixes A11-1471

### CODE REVIEW

**Comment by ap-nri** [comment]
@tesk9 sorry this got a little stale and there are some conflicts now

**Comment by tesk9** [comment]
Should be fixed!

**Review by ap-nri — APPROVED** [review]
@NoRedInkBot r+ even though you have no power here.

**Comment by ap-nri** [comment]
oh wow Bors is Borsing. Feel free to merge if it fails to Bors

**Pull request merged**
